# Auto-generated test file
# Generated at: 20251021_222433
# Target path: tests/unit/test_services/test_order_management_services.py
# Do NOT edit this file manually - regenerate from source models

"""
Order_Management service tests generated by ServiceTestGenerator.

Generated: 2025-10-21 14:24:33
Strategy: repository mocks only.
"""

import inspect
from types import SimpleNamespace
from decimal import Decimal
from datetime import datetime, timedelta
import pytest
from pytest_mock import MockerFixture

from app.modules.order_management.models import Order, OrderItem, OrderStatus, OrderStatusHistory
from app.modules.order_management.repository import OrderRepository

try:
    from app.modules.order_management.service import OrderService
    SERVICE_AVAILABLE = True
except ImportError:
    SERVICE_AVAILABLE = False

def _pick_dependency(context: dict, keyword: str):
    for name, value in context.items():
        if name == "service":
            continue
        if keyword.lower() in name.lower():
            return value
    return None


def _make_namespace(**overrides):
    defaults = {
        "id": 1,
        "status": "pending",
        "amount": Decimal("99.99"),
        "order_id": 1,
        "user_id": 1,
        "payment_reference": "PAY-AUTO-001",
        "description": "auto generated",
    }
    defaults.update(overrides)
    return SimpleNamespace(**defaults)


def _make_session_mock(mocker: MockerFixture):
    session = mocker.MagicMock(name="OrderService_session")
    session.begin.return_value.__enter__.return_value = session
    session.begin.return_value.__exit__.return_value = False
    session.begin_nested.return_value.__enter__.return_value = session
    session.begin_nested.return_value.__exit__.return_value = False
    query = session.query.return_value
    query.filter.return_value = query
    query.filter_by.return_value = query
    query.one_or_none.return_value = _make_namespace()
    query.all.return_value = []
    query.count.return_value = 0
    session.refresh.side_effect = lambda entity: setattr(entity, "id", getattr(entity, "id", 1))
    session.commit.return_value = None
    session.rollback.return_value = None
    return session


def _configure_repository_session(repository_mock, mocker: MockerFixture):
    session = _make_session_mock(mocker)
    repository_mock.session = session
    return session


async def _run_in_thread_passthrough(func, *args, **kwargs):
    result = func(*args, **kwargs)
    if inspect.isawaitable(result):
        return await result
    return result


@pytest.fixture
def service_context(mocker: MockerFixture):
    if not SERVICE_AVAILABLE:
        pytest.skip("service import failed")

    service_cls = OrderService
    signature = inspect.signature(service_cls)
    init_kwargs = {}
    context = {}

    for name, param in signature.parameters.items():
        if name == "self":
            continue
        dependency = mocker.MagicMock(name=name)
        context[name] = dependency
        init_kwargs[name] = dependency
        if "repository" in name.lower():
            _configure_repository_session(dependency, mocker)

    service = service_cls(**init_kwargs)
    context["service"] = service
    return context

@pytest.mark.unit
@pytest.mark.services
class TestOrderService:
    """Service layer tests relying on mocked repositories."""

    def test_service_initialization(self, service_context: dict) -> None:
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        assert service_context["service"] is not None

    @pytest.mark.asyncio
    async def test_create_order_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise create_order success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            user_stub = _make_namespace()
            order_repository.get_user_by_id.return_value = user_stub
        _create_order_with_transaction__create_order_with_transaction_mock = mocker.patch.object(service, "_create_order_with_transaction", new=mocker.AsyncMock(return_value=_make_namespace(id=1, status="pending")))
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        _validate_and_reserve_stock__validate_and_reserve_stock_mock = mocker.patch.object(service, "_validate_and_reserve_stock", new=mocker.AsyncMock(return_value=None))
        _validate_products_and_calculate_amount__validate_products_and_calculate_amount_mock = mocker.patch.object(service, "_validate_products_and_calculate_amount", new=mocker.AsyncMock(return_value=(Decimal("0.00"), [])))
        order_data = _make_namespace(items=[_make_namespace(product_id=1, sku_id=1, quantity=1)])
        user_id = 1
        result = await service.create_order(order_data=order_data, user_id=user_id)
        assert result is not None

    @pytest.mark.asyncio
    async def test_get_order_by_id_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_order_by_id success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_stub = _make_namespace(user_id=1)
            order_repository.get_order_by_id.return_value = order_stub
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        order_id = 1
        user_id = None
        result = await service.get_order_by_id(order_id=order_id, user_id=user_id)
        assert result is not None

    @pytest.mark.asyncio
    async def test_get_orders_list_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_orders_list success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_repository.list_orders.return_value = []
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        user_id = None
        status = _make_namespace(HTTP_500_INTERNAL_SERVER_ERROR="value")
        skip = 0
        limit = 100
        result = await service.get_orders_list(user_id=user_id, status=status, skip=skip, limit=limit)
        assert result is not None

    @pytest.mark.asyncio
    async def test_update_order_status_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise update_order_status success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        isinstance_call_mock = mocker.patch("app.modules.order_management.service.isinstance")
        isinstance_call_mock.return_value = None
        OrderStatusHistory_call_mock = mocker.patch("app.modules.order_management.service.OrderStatusHistory")
        OrderStatusHistory_call_mock.return_value = None
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_stub = _make_namespace(id=1, status="pending")
            order_repository.get_order_with_items.return_value = order_stub
            order_repository.save_status_history.return_value = None
            order_repository.commit.return_value = None
            order_repository.refresh.return_value = None
            order_repository.rollback.return_value = None
        _handle_status_change_business_logic__handle_status_change_business_logic_mock = mocker.patch.object(service, "_handle_status_change_business_logic", new=mocker.AsyncMock(return_value=None))
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        _is_valid_status_transition__is_valid_status_transition_mock = mocker.patch.object(service, "_is_valid_status_transition")
        _is_valid_status_transition__is_valid_status_transition_mock.return_value = True
        order_id = 1
        new_status = "paid"
        operator_id = 1
        remark = None
        result = await service.update_order_status(order_id=order_id, new_status=new_status, operator_id=operator_id, remark=remark)
        assert result is not None

    @pytest.mark.asyncio
    async def test_cancel_order_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise cancel_order success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_stub = _make_namespace(status="pending")
            order_repository.get_order_with_items.return_value = order_stub
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        order_id = 1
        operator_id = 1
        reason = None
        result = await service.cancel_order(order_id=order_id, operator_id=operator_id, reason=reason)
        assert result is not None
        if order_repository:
            order_repository.get_order_with_items.assert_called()

    @pytest.mark.asyncio
    async def test_get_order_items_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_order_items success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_repository.get_order_items.return_value = _make_namespace()
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        order_id = 1
        user_id = None
        result = await service.get_order_items(order_id=order_id, user_id=user_id)
        assert result is not None

    @pytest.mark.asyncio
    async def test_get_order_status_history_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_order_status_history success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_repository.get_order_status_history.return_value = _make_namespace()
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        order_id = 1
        result = await service.get_order_status_history(order_id=order_id)
        assert result is not None

    @pytest.mark.asyncio
    async def test_calculate_order_statistics_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise calculate_order_statistics success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        round_call_mock = mocker.patch("app.modules.order_management.service.round")
        round_call_mock.return_value = None
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_repository.calculate_order_statistics.return_value = {'total_orders': 1, 'delivered_orders': 1, 'cancelled_orders': 0}
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        user_id = None
        result = await service.calculate_order_statistics(user_id=user_id)
        assert result is not None

    @pytest.mark.asyncio
    async def test_get_orders_by_status_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_orders_by_status success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        order_repository = context.get("order_repository") or _pick_dependency(context, "order_repository")
        if order_repository:
            order_repository.get_orders_by_status.return_value = _make_namespace()
        _http_error__http_error_mock = mocker.patch.object(service, "_http_error")
        _http_error__http_error_mock.return_value = None
        status = _make_namespace(HTTP_500_INTERNAL_SERVER_ERROR="value")
        limit = 100
        result = await service.get_orders_by_status(status=status, limit=limit)
        assert result is not None

