# Auto-generated test file
# Generated at: 20251021_220216
# Target path: tests/unit/test_services/test_user_auth_services.py
# Do NOT edit this file manually - regenerate from source models

"""
User_Auth service tests generated by ServiceTestGenerator.

Generated: 2025-10-21 14:02:16
Strategy: repository mocks only.
"""

import inspect
from types import SimpleNamespace
from decimal import Decimal
from datetime import datetime, timedelta
import pytest
from pytest_mock import MockerFixture

from app.modules.user_auth.models import Permission, UserRole, Session, Role, User, RolePermission
from app.modules.user_auth.repository import PermissionRepository, RolePermissionRepository, RoleRepository, SessionRepository, UserRepository, UserRoleRepository

try:
    from app.modules.user_auth.service import UserService
    SERVICE_AVAILABLE = True
except ImportError:
    SERVICE_AVAILABLE = False

def _pick_dependency(context: dict, keyword: str):
    for name, value in context.items():
        if name == "service":
            continue
        if keyword.lower() in name.lower():
            return value
    return None


def _make_namespace(**overrides):
    defaults = {
        "id": 1,
        "status": "pending",
        "amount": Decimal("99.99"),
        "order_id": 1,
        "user_id": 1,
        "payment_reference": "PAY-AUTO-001",
        "description": "auto generated",
    }
    defaults.update(overrides)
    return SimpleNamespace(**defaults)


def _make_session_mock(mocker: MockerFixture):
    session = mocker.MagicMock(name="UserService_session")
    session.begin.return_value.__enter__.return_value = session
    session.begin.return_value.__exit__.return_value = False
    session.begin_nested.return_value.__enter__.return_value = session
    session.begin_nested.return_value.__exit__.return_value = False
    query = session.query.return_value
    query.filter.return_value = query
    query.filter_by.return_value = query
    query.one_or_none.return_value = _make_namespace()
    query.all.return_value = []
    query.count.return_value = 0
    session.refresh.side_effect = lambda entity: setattr(entity, "id", getattr(entity, "id", 1))
    session.commit.return_value = None
    session.rollback.return_value = None
    return session


def _configure_repository_session(repository_mock, mocker: MockerFixture):
    session = _make_session_mock(mocker)
    repository_mock.session = session
    return session


async def _run_in_thread_passthrough(func, *args, **kwargs):
    result = func(*args, **kwargs)
    if inspect.isawaitable(result):
        return await result
    return result


@pytest.fixture
def service_context(mocker: MockerFixture):
    if not SERVICE_AVAILABLE:
        pytest.skip("service import failed")

    service_cls = UserService
    signature = inspect.signature(service_cls)
    init_kwargs = {}
    context = {}

    for name, param in signature.parameters.items():
        if name == "self":
            continue
        dependency = mocker.MagicMock(name=name)
        context[name] = dependency
        init_kwargs[name] = dependency
        if "repository" in name.lower():
            _configure_repository_session(dependency, mocker)

    service = service_cls(**init_kwargs)
    context["service"] = service
    return context

@pytest.mark.unit
@pytest.mark.services
class TestUserService:
    """Service layer tests relying on mocked repositories."""

    def test_service_initialization(self, service_context: dict) -> None:
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        assert service_context["service"] is not None

    def test_create_user_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise create_user success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        get_password_hash_call_mock = mocker.patch("app.modules.user_auth.service.get_password_hash")
        get_password_hash_call_mock.return_value = "hashed"
        User_call_mock = mocker.patch("app.modules.user_auth.service.User")
        User_call_mock.return_value = None
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_check_exists_mock = mocker.patch.object(UserRepository, "check_exists")
        UserRepository_check_exists_mock.return_value = False
        UserRepository_create_mock = mocker.patch.object(UserRepository, "create")
        user_stub = _make_namespace()
        UserRepository_create_mock.return_value = user_stub
        db = _make_session_mock(mocker)
        username = _make_namespace(id=1, status="active")
        email = "value@example.com"
        password = "value"
        phone = "13800138000"
        real_name = None
        role = 'user'
        is_active = True
        result = service.create_user(db=db, username=username, email=email, password=password, phone=phone, real_name=real_name, role=role, is_active=is_active)
        assert result is not None
        UserRepository_check_exists_mock.assert_called()

    def test_authenticate_user_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise authenticate_user success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        verify_password_call_mock = mocker.patch("app.modules.user_auth.service.verify_password")
        verify_password_call_mock.return_value = True
        now_call_mock = mocker.patch("app.modules.user_auth.service.datetime")
        now_call_mock.now.return_value = datetime.utcnow()
        UserRepository_get_by_username_or_email_mock = mocker.patch.object(UserRepository, "get_by_username_or_email")
        user_stub = _make_namespace(locked_until=datetime.utcnow() - timedelta(minutes=5), password_hash="value")
        UserRepository_get_by_username_or_email_mock.return_value = user_stub
        db = _make_session_mock(mocker)
        username = _make_namespace(id=1, status="active")
        password = "value"
        result = service.authenticate_user(db=db, username=username, password=password)
        assert result is not None
        UserRepository_get_by_username_or_email_mock.assert_called()

    def test_get_user_by_id_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_user_by_id success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        UserRepository_get_by_id_mock = mocker.patch.object(UserRepository, "get_by_id")
        UserRepository_get_by_id_mock.return_value = _make_namespace()
        db = _make_session_mock(mocker)
        user_id = 1
        result = service.get_user_by_id(db=db, user_id=user_id)
        assert result is not None
        UserRepository_get_by_id_mock.assert_called()

    def test_get_users_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_users success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        UserRepository_list_mock = mocker.patch.object(UserRepository, "list")
        UserRepository_list_mock.return_value = []
        db = _make_session_mock(mocker)
        skip = 0
        limit = 100
        result = service.get_users(db=db, skip=skip, limit=limit)
        assert result is not None
        UserRepository_list_mock.assert_called()

    def test_update_user_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise update_user success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_id_mock = mocker.patch.object(UserRepository, "get_by_id")
        user_stub = _make_namespace()
        UserRepository_get_by_id_mock.return_value = user_stub
        UserRepository_update_mock = mocker.patch.object(UserRepository, "update")
        user_stub = _make_namespace()
        UserRepository_update_mock.return_value = user_stub
        db = _make_session_mock(mocker)
        user_id = 1
        result = service.update_user(db=db, user_id=user_id)
        assert result is not None
        UserRepository_get_by_id_mock.assert_called()

    def test_change_password_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise change_password success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        get_password_hash_call_mock = mocker.patch("app.modules.user_auth.service.get_password_hash")
        get_password_hash_call_mock.return_value = "hashed"
        verify_password_call_mock = mocker.patch("app.modules.user_auth.service.verify_password")
        verify_password_call_mock.return_value = True
        UserRepository_get_by_id_mock = mocker.patch.object(UserRepository, "get_by_id")
        user_stub = _make_namespace(password_hash="value")
        UserRepository_get_by_id_mock.return_value = user_stub
        UserRepository_update_mock = mocker.patch.object(UserRepository, "update")
        UserRepository_update_mock.return_value = None
        db = _make_session_mock(mocker)
        user_id = 1
        old_password = "value"
        new_password = "value"
        result = service.change_password(db=db, user_id=user_id, old_password=old_password, new_password=new_password)
        assert result is not None
        UserRepository_get_by_id_mock.assert_called()
        UserRepository_update_mock.assert_called()

    def test_generate_tokens_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise generate_tokens success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        create_access_token_call_mock = mocker.patch("app.modules.user_auth.service.create_access_token")
        create_access_token_call_mock.return_value = "access"
        user = _make_namespace(id=1, username="value")
        result = service.generate_tokens(user=user)
        assert result is not None

    @pytest.mark.asyncio
    async def test_register_user_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise register_user success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        run_in_thread_call_mock = mocker.patch("app.modules.user_auth.service.run_in_thread", new=_run_in_thread_passthrough)
        get_password_hash_call_mock = mocker.patch("app.modules.user_auth.service.get_password_hash")
        get_password_hash_call_mock.return_value = "hashed"
        User_call_mock = mocker.patch("app.modules.user_auth.service.User")
        User_call_mock.return_value = None
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_username_mock = mocker.patch.object(UserRepository, "get_by_username")
        UserRepository_get_by_username_mock.return_value = None
        UserRepository_get_by_email_mock = mocker.patch.object(UserRepository, "get_by_email")
        UserRepository_get_by_email_mock.return_value = None
        UserRepository_create_mock = mocker.patch.object(UserRepository, "create")
        created_user_stub = _make_namespace()
        UserRepository_create_mock.return_value = created_user_stub
        UserService_generate_tokens_mock = mocker.patch("app.modules.user_auth.service.UserService.generate_tokens")
        UserService_generate_tokens_mock.return_value = {"access_token": "access", "refresh_token": "refresh", "token_type": "bearer"}
        VerificationCodeService_verify_code_mock = mocker.patch("app.core.verification.VerificationCodeService.verify_code", new=mocker.AsyncMock(return_value=True))
        db = _make_session_mock(mocker)
        username = _make_namespace(id=1, status="active")
        email = "value@example.com"
        password = "value"
        verification_code = "value"
        phone = "13800138000"
        real_name = None
        result = await service.register_user(db=db, username=username, email=email, password=password, verification_code=verification_code, phone=phone, real_name=real_name)
        assert result is not None
        UserRepository_get_by_email_mock.assert_called()
        UserRepository_get_by_username_mock.assert_called()
        VerificationCodeService_verify_code_mock.assert_called()

    @pytest.mark.asyncio
    async def test_login_user_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise login_user success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        run_in_thread_call_mock = mocker.patch("app.modules.user_auth.service.run_in_thread", new=_run_in_thread_passthrough)
        create_access_token_call_mock = mocker.patch("app.modules.user_auth.service.create_access_token")
        create_access_token_call_mock.return_value = "access"
        create_refresh_token_call_mock = mocker.patch("app.modules.user_auth.service.create_refresh_token")
        create_refresh_token_call_mock.return_value = "refresh"
        log_security_event_call_mock = mocker.patch("app.core.security_logger.log_security_event")
        log_security_event_call_mock.return_value = None
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_username_or_email_mock = mocker.patch.object(UserRepository, "get_by_username_or_email")
        user_for_check_stub = _make_namespace(email="value@example.com", failed_login_attempts=0)
        UserRepository_get_by_username_or_email_mock.return_value = user_for_check_stub
        UserRepository_increment_failed_login_mock = mocker.patch.object(UserRepository, "increment_failed_login")
        UserRepository_increment_failed_login_mock.return_value = None
        UserRepository_update_login_info_mock = mocker.patch.object(UserRepository, "update_login_info")
        UserRepository_update_login_info_mock.return_value = None
        UserService_authenticate_user_mock = mocker.patch("app.modules.user_auth.service.UserService.authenticate_user")
        UserService_authenticate_user_mock.return_value = _make_namespace(id=1, status="active")
        VerificationCodeService_verify_code_mock = mocker.patch("app.core.verification.VerificationCodeService.verify_code", new=mocker.AsyncMock(return_value=True))
        db = _make_session_mock(mocker)
        username = _make_namespace(id=1, status="active")
        password = "value"
        verification_code = None
        result = await service.login_user(db=db, username=username, password=password, verification_code=verification_code)
        assert result is not None
        UserRepository_get_by_username_or_email_mock.assert_called()
        UserRepository_update_login_info_mock.assert_called()
        UserService_authenticate_user_mock.assert_called()

    def test_refresh_access_token_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise refresh_access_token success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        AuthenticationError_call_mock = mocker.patch("app.core.auth.AuthenticationError")
        AuthenticationError_call_mock.side_effect = Exception
        create_access_token_call_mock = mocker.patch("app.modules.user_auth.service.create_access_token")
        create_access_token_call_mock.return_value = "access"
        create_refresh_token_call_mock = mocker.patch("app.modules.user_auth.service.create_refresh_token")
        create_refresh_token_call_mock.return_value = "refresh"
        decode_token_call_mock = mocker.patch("app.core.auth.decode_token")
        decode_token_call_mock.return_value = {'sub': 1, 'type': 'refresh'}
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_id_mock = mocker.patch.object(UserRepository, "get_by_id")
        user_stub = _make_namespace(get="value", id=1, is_active=True)
        UserRepository_get_by_id_mock.return_value = user_stub
        db = _make_session_mock(mocker)
        refresh_token = "value"
        result = service.refresh_access_token(db=db, refresh_token=refresh_token)
        assert result is not None

    def test_update_user_info_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise update_user_info success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_id_mock = mocker.patch.object(UserRepository, "get_by_id")
        user_stub = _make_namespace()
        UserRepository_get_by_id_mock.return_value = user_stub
        UserRepository_get_by_email_mock = mocker.patch.object(UserRepository, "get_by_email")
        existing_user_stub = _make_namespace(id=1)
        UserRepository_get_by_email_mock.return_value = existing_user_stub
        UserRepository_update_mock = mocker.patch.object(UserRepository, "update")
        user_stub = _make_namespace()
        UserRepository_update_mock.return_value = user_stub
        db = _make_session_mock(mocker)
        user_id = 1
        email = "value@example.com"
        phone = "13800138000"
        real_name = None
        result = service.update_user_info(db=db, user_id=user_id, email=email, phone=phone, real_name=real_name)
        assert result is not None
        UserRepository_get_by_id_mock.assert_called()

    def test_change_user_password_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise change_user_password success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        get_password_hash_call_mock = mocker.patch("app.modules.user_auth.service.get_password_hash")
        get_password_hash_call_mock.return_value = "hashed"
        verify_password_call_mock = mocker.patch("app.modules.user_auth.service.verify_password")
        verify_password_call_mock.return_value = True
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_id_mock = mocker.patch.object(UserRepository, "get_by_id")
        user_stub = _make_namespace(password_hash="value")
        UserRepository_get_by_id_mock.return_value = user_stub
        UserRepository_update_mock = mocker.patch.object(UserRepository, "update")
        UserRepository_update_mock.return_value = None
        db = _make_session_mock(mocker)
        user_id = 1
        old_password = "value"
        new_password = "value"
        result = service.change_user_password(db=db, user_id=user_id, old_password=old_password, new_password=new_password)
        assert result is not None
        UserRepository_get_by_id_mock.assert_called()

    def test_get_user_list_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise get_user_list success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        UserRepository_list_mock = mocker.patch.object(UserRepository, "list")
        UserRepository_list_mock.return_value = []
        db = _make_session_mock(mocker)
        skip = 0
        limit = 100
        result = service.get_user_list(db=db, skip=skip, limit=limit)
        assert result is not None
        UserRepository_list_mock.assert_called()

    @pytest.mark.asyncio
    async def test_send_verification_code_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise send_verification_code success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        run_in_thread_call_mock = mocker.patch("app.modules.user_auth.service.run_in_thread", new=_run_in_thread_passthrough)
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_email_mock = mocker.patch.object(UserRepository, "get_by_email")
        UserRepository_get_by_email_mock.return_value = None
        UserRepository_get_by_email_mock = mocker.patch.object(UserRepository, "get_by_email")
        UserRepository_get_by_email_mock.return_value = None
        UserRepository_get_by_phone_mock = mocker.patch.object(UserRepository, "get_by_phone")
        user_stub = _make_namespace()
        UserRepository_get_by_phone_mock.return_value = user_stub
        VerificationCodeService_send_verification_code_mock = mocker.patch("app.core.verification.VerificationCodeService.send_verification_code", new=mocker.AsyncMock(return_value={"message": "ok"}))
        os_getenv_mock = mocker.patch("os.getenv")
        os_getenv_mock.return_value = None
        db = _make_session_mock(mocker)
        email = "value@example.com"
        phone = "13800138000"
        code_type = 'register'
        result = await service.send_verification_code(db=db, email=email, phone=phone, code_type=code_type)
        assert result is not None
        VerificationCodeService_send_verification_code_mock.assert_called()
        os_getenv_mock.assert_called()

    @pytest.mark.asyncio
    async def test_phone_login_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise phone_login success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        run_in_thread_call_mock = mocker.patch("app.modules.user_auth.service.run_in_thread", new=_run_in_thread_passthrough)
        create_access_token_call_mock = mocker.patch("app.modules.user_auth.service.create_access_token")
        create_access_token_call_mock.return_value = "access"
        create_refresh_token_call_mock = mocker.patch("app.modules.user_auth.service.create_refresh_token")
        create_refresh_token_call_mock.return_value = "refresh"
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_phone_mock = mocker.patch.object(UserRepository, "get_by_phone")
        user_stub = _make_namespace(id=1, is_active=True)
        UserRepository_get_by_phone_mock.return_value = user_stub
        UserRepository_update_login_info_mock = mocker.patch.object(UserRepository, "update_login_info")
        UserRepository_update_login_info_mock.return_value = None
        VerificationCodeService_verify_code_mock = mocker.patch("app.core.verification.VerificationCodeService.verify_code", new=mocker.AsyncMock(return_value=True))
        db = _make_session_mock(mocker)
        phone = "13800138000"
        verification_code = "value"
        result = await service.phone_login(db=db, phone=phone, verification_code=verification_code)
        assert result is not None
        UserRepository_get_by_phone_mock.assert_called()
        UserRepository_update_login_info_mock.assert_called()
        VerificationCodeService_verify_code_mock.assert_called()

    @pytest.mark.asyncio
    async def test_reset_password_request_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise reset_password_request success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        UserService_send_verification_code_mock = mocker.patch("app.modules.user_auth.service.UserService.send_verification_code", new=mocker.AsyncMock(return_value={"message": "ok"}))
        db = _make_session_mock(mocker)
        email = "value@example.com"
        result = await service.reset_password_request(db=db, email=email)
        assert result is not None
        UserService_send_verification_code_mock.assert_called()

    @pytest.mark.asyncio
    async def test_reset_password_confirm_success(self, mocker: MockerFixture, service_context: dict) -> None:
        """Exercise reset_password_confirm success path."""
        if not SERVICE_AVAILABLE:
            pytest.skip("service import failed")
        context = service_context
        service = context["service"]
        run_in_thread_call_mock = mocker.patch("app.modules.user_auth.service.run_in_thread", new=_run_in_thread_passthrough)
        get_password_hash_call_mock = mocker.patch("app.modules.user_auth.service.get_password_hash")
        get_password_hash_call_mock.return_value = "hashed"
        HTTPException_call_mock = mocker.patch("app.modules.user_auth.service.HTTPException")
        HTTPException_call_mock.side_effect = Exception
        UserRepository_get_by_email_mock = mocker.patch.object(UserRepository, "get_by_email")
        user_stub = _make_namespace()
        UserRepository_get_by_email_mock.return_value = user_stub
        UserRepository_update_mock = mocker.patch.object(UserRepository, "update")
        UserRepository_update_mock.return_value = None
        VerificationCodeService_verify_code_mock = mocker.patch("app.core.verification.VerificationCodeService.verify_code", new=mocker.AsyncMock(return_value=True))
        db = _make_session_mock(mocker)
        email = "value@example.com"
        verification_code = "value"
        new_password = "value"
        result = await service.reset_password_confirm(db=db, email=email, verification_code=verification_code, new_password=new_password)
        assert result is not None
        UserRepository_get_by_email_mock.assert_called()
        VerificationCodeService_verify_code_mock.assert_called()

