version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # In dev we install requirements inside the container to avoid host/.venv ABI issues
    command: bash -c "pip install -r requirements.txt && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app:cached
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
