# Auto-generated test file
# Generated at: 20251011_071006
# Target path: tests/unit/test_repositories/test_product_catalog_repositories.py
# Do NOT edit this file manually - regenerate from source models

"""
Auto Generated Test - Repository Layer

文件路径: tests/unit/test_repositories/test_product_catalog_repositories.py
生成时间: 2025-10-11 07:10:03
生成工具: tools/generate_test_template.py v3.0
模块: product_catalog

测试类型: 单元测试 - Repository数据访问层
测试策略: SQLite内存数据库
测试重点: 
- CRUD操作正确性
- 查询条件和过滤逻辑
- 事务提交和回滚
- 边界情况和错误处理

符合标准: 
- testing-standards.md - 四层架构测试策略
- architecture/overview.md - Repository模式标准

[CHECK:TEST-001] [CHECK:DEV-009]
"""

import pytest
from typing import List, Optional
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timedelta
from decimal import Decimal

# 导入测试基础设施
from tests.conftest import unit_test_db

# 导入Repository类
from app.modules.product_catalog.repository import (
    CategoryRepository, BrandRepository, ProductRepository, SKURepository
)

# 导入模型类
from app.modules.product_catalog.models import (
    Brand, Category, Product, SKU
)


@pytest.mark.unit
@pytest.mark.repositories
class TestCategoryRepository:
    """
    CategoryRepository 数据访问层测试
    
    测试范围:
    - 7 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
# 创建最小实体（只填必填字段）
        entity = Category(
            name="name",
            sort_order=1,
            is_active=False
        )
        
        # 执行Repository方法
        result = CategoryRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Category).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用Factory Boy
        """
        # 使用Factory Boy创建完整实体
        from tests.factories.product_catalog_factories import CategoryFactory
        entity = CategoryFactory.build()  # build不自动保存到数据库
        
        # 执行Repository方法
        result = CategoryRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Category).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证数据真正写入数据库
        """
        from tests.factories.product_catalog_factories import CategoryFactory
        entity = CategoryFactory.build()
        
        result = CategoryRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Category).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备依赖实体
        category = Category(name="Category数据", sort_order=1, is_active=True)
        unit_test_db.add(category)
        unit_test_db.commit()
        
        # 准备测试数据
        entity = Category(name="查询测试", sort_order=1, is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = CategoryRepository.get_by_id(unit_test_db, category.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = CategoryRepository.get_by_id(unit_test_db, "nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = Category(name="查询测试", sort_order=1, is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = CategoryRepository.list(unit_test_db, entity.id, None, 0, 0)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_children_query(self, unit_test_db: Session):
        """测试children - 查询功能"""
        # 准备测试数据
        entity = Category(name="查询测试", sort_order=1, is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = CategoryRepository.children(unit_test_db, entity.id)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_count_children_query(self, unit_test_db: Session):
        """测试count_children - 查询功能"""
        # 准备测试数据
        entity = Category(name="查询测试", sort_order=1, is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = CategoryRepository.count_children(unit_test_db, entity.id)
        
        # 验证查询结果
        assert result >= 0  # count方法返回int

    def test_find_by_name_and_parent_found(self, unit_test_db: Session):
        """测试find_by_name_and_parent - 查询到数据"""
        # 准备测试数据
        entity = Category(name="查询测试", sort_order=1, is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = CategoryRepository.find_by_name_and_parent(unit_test_db, entity.name, None, None)
        
        # 验证结果
        assert result is not None
        assert result.name == entity.name
    
    def test_find_by_name_and_parent_not_found(self, unit_test_db: Session):
        """测试find_by_name_and_parent - 数据不存在"""
        result = CategoryRepository.find_by_name_and_parent(unit_test_db, "nonexistent_value", None, None)
        
        assert result is None

    def test_count_products_query(self, unit_test_db: Session):
        """测试count_products - 查询功能"""
        # 准备测试数据
        entity = Category(name="查询测试", sort_order=1, is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = CategoryRepository.count_products(unit_test_db, entity.id)
        
        # 验证查询结果
        assert result >= 0  # count方法返回int




@pytest.mark.unit
@pytest.mark.repositories
class TestBrandRepository:
    """
    BrandRepository 数据访问层测试
    
    测试范围:
    - 5 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
# 创建最小实体（只填必填字段）
        entity = Brand(
            name="name",
            slug="slug",
            is_active=False
        )
        
        # 执行Repository方法
        result = BrandRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Brand).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用Factory Boy
        """
        # 使用Factory Boy创建完整实体
        from tests.factories.product_catalog_factories import BrandFactory
        entity = BrandFactory.build()  # build不自动保存到数据库
        
        # 执行Repository方法
        result = BrandRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Brand).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证数据真正写入数据库
        """
        from tests.factories.product_catalog_factories import BrandFactory
        entity = BrandFactory.build()
        
        result = BrandRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Brand).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备依赖实体
        brand = Brand(name="Brand数据", slug="test-brand数据", is_active=True)
        unit_test_db.add(brand)
        unit_test_db.commit()
        
        # 准备测试数据
        entity = Brand(name="查询测试", slug="test-查询测试", is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = BrandRepository.get_by_id(unit_test_db, brand.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = BrandRepository.get_by_id(unit_test_db, "nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = Brand(name="查询测试", slug="test-查询测试", is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = BrandRepository.list(unit_test_db)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_update_single_field(self, unit_test_db: Session):
        """测试update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        """
        # 准备测试数据
        from tests.factories.product_catalog_factories import BrandFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = BrandFactory.create()
        original_slug = entity.slug
        
        # 执行Repository方法（只更新name）
        update_data = {"name": "更新后数据"}
        result = BrandRepository.update(unit_test_db, entity, update_data)  # TODO: 根据实际方法签名调整
        
        # 验证目标字段已更新
        assert result.name == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.slug == original_slug
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Brand).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据"
        assert db_entity.slug == original_slug
    
    def test_update_multiple_fields(self, unit_test_db: Session):
        """测试update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        """
        from tests.factories.product_catalog_factories import BrandFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = BrandFactory.create()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "name": "更新后数据1",
            "slug": "更新后数据2"
        }
        result = BrandRepository.update(unit_test_db, entity, update_data)
        
        # 验证所有字段已更新
        assert result.name == "更新后数据1"
        assert result.slug == "更新后数据2"
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Brand).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据1"
        assert db_entity.slug == "更新后数据2"
    
    def test_update_transaction_commit(self, unit_test_db: Session):
        """测试update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        """
        from tests.factories.product_catalog_factories import BrandFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = BrandFactory.create()
        
        update_data = {"name": "事务测试数据"}
        result = BrandRepository.update(unit_test_db, entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Brand).filter_by(id=entity.id).first()
        assert db_entity.name == "事务测试数据"
    
    def test_update_specialized_method(self, unit_test_db: Session):
        """测试update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = BrandFactory.create(status='active')
        # result = BrandRepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    def test_soft_delete_success(self, unit_test_db: Session):
        """测试soft_delete - 删除成功"""
        # 准备测试数据
        entity = Brand(name="待删除数据", slug="test-待删除数据", is_active=True)
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        BrandRepository.soft_delete(unit_test_db, entity)
        
        # 验证软删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Brand).filter_by(id=entity_id).first()
        assert db_entity is not None  # 记录仍存在
        # 验证软删除标记（根据模型字段选择）
        if hasattr(db_entity, 'is_deleted'):
            assert db_entity.is_deleted == True
        if hasattr(db_entity, 'is_active'):
            assert db_entity.is_active == False




@pytest.mark.unit
@pytest.mark.repositories
class TestProductRepository:
    """
    ProductRepository 数据访问层测试
    
    测试范围:
    - 5 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
# 创建最小实体（只填必填字段）
        entity = Product(
            name="name",
            status="status",
            sort_order=1,
            view_count=1,
            sale_count=1
        )
        
        # 执行Repository方法
        result = ProductRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Product).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用Factory Boy
        """
        # 使用Factory Boy创建完整实体
        from tests.factories.product_catalog_factories import ProductFactory
        entity = ProductFactory.build()  # build不自动保存到数据库
        
        # 执行Repository方法
        result = ProductRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Product).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证数据真正写入数据库
        """
        from tests.factories.product_catalog_factories import ProductFactory
        entity = ProductFactory.build()
        
        result = ProductRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Product).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备依赖实体
        product = Product(name="Product数据", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(product)
        unit_test_db.commit()
        
        # 准备测试数据
        entity = Product(name="查询测试", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = ProductRepository.get_by_id(unit_test_db, product.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = ProductRepository.get_by_id(unit_test_db, "nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = Product(name="查询测试", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = ProductRepository.list(unit_test_db, 0, 0)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_update_single_field(self, unit_test_db: Session):
        """测试update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        """
        # 准备测试数据
        from tests.factories.product_catalog_factories import ProductFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = ProductFactory.create()
        original_description = entity.description
        
        # 执行Repository方法（只更新name）
        update_data = {"name": "更新后数据"}
        result = ProductRepository.update(unit_test_db, entity, update_data)  # TODO: 根据实际方法签名调整
        
        # 验证目标字段已更新
        assert result.name == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.description == original_description
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Product).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据"
        assert db_entity.description == original_description
    
    def test_update_multiple_fields(self, unit_test_db: Session):
        """测试update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        """
        from tests.factories.product_catalog_factories import ProductFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = ProductFactory.create()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "name": "更新后数据1",
            "description": "更新后数据2"
        }
        result = ProductRepository.update(unit_test_db, entity, update_data)
        
        # 验证所有字段已更新
        assert result.name == "更新后数据1"
        assert result.description == "更新后数据2"
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Product).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据1"
        assert db_entity.description == "更新后数据2"
    
    def test_update_transaction_commit(self, unit_test_db: Session):
        """测试update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        """
        from tests.factories.product_catalog_factories import ProductFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = ProductFactory.create()
        
        update_data = {"name": "事务测试数据"}
        result = ProductRepository.update(unit_test_db, entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Product).filter_by(id=entity.id).first()
        assert db_entity.name == "事务测试数据"
    
    def test_update_specialized_method(self, unit_test_db: Session):
        """测试update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = ProductFactory.create(status='active')
        # result = ProductRepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    def test_soft_delete_success(self, unit_test_db: Session):
        """测试soft_delete - 删除成功"""
        # 准备测试数据
        entity = Product(name="待删除数据", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        ProductRepository.soft_delete(unit_test_db, entity)
        
        # 验证软删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Product).filter_by(id=entity_id).first()
        assert db_entity is not None  # 记录仍存在
        # 验证软删除标记（根据模型字段选择）
        if hasattr(db_entity, 'is_deleted'):
            assert db_entity.is_deleted == True
        if hasattr(db_entity, 'is_active'):
            assert db_entity.is_active == False




@pytest.mark.unit
@pytest.mark.repositories
class TestSKURepository:
    """
    SKURepository 数据访问层测试
    
    测试范围:
    - 6 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.product_catalog_factories import ProductFactory
        from tests.factories.product_catalog_factories import ProductCatalogFactoryManager
        # 创建最小实体（只填必填字段）
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        product = ProductFactory.create()
        
        entity = SKU(
            sku_code="sku_code",
            price=0.01,
            is_active=False,
            product_id=product.id
        )
        
        # 执行Repository方法
        result = SKURepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(SKU).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用Factory Boy
        """
        # 使用Factory Boy创建完整实体
        from tests.factories.product_catalog_factories import SKUFactory
        entity = SKUFactory.build()  # build不自动保存到数据库
        
        # 执行Repository方法
        result = SKURepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(SKU).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证数据真正写入数据库
        """
        from tests.factories.product_catalog_factories import SKUFactory
        entity = SKUFactory.build()
        
        result = SKURepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(SKU).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备依赖实体
        sku = product = Product(name="依赖SKU数据", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(product)
        unit_test_db.commit()
        entity = SKU(sku_code="TESTSKU数据", price=Decimal("10.00"), is_active=True, product_id=product.id)
        unit_test_db.add(sku)
        unit_test_db.commit()
        
        # 准备测试数据
        entity = product = Product(name="依赖查询测试", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(product)
        unit_test_db.commit()
        entity = SKU(sku_code="TEST查询测试", price=Decimal("10.00"), is_active=True, product_id=product.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SKURepository.get_by_id(unit_test_db, sku.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = SKURepository.get_by_id(unit_test_db, "nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = product = Product(name="依赖查询测试", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(product)
        unit_test_db.commit()
        entity = SKU(sku_code="TEST查询测试", price=Decimal("10.00"), is_active=True, product_id=product.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = SKURepository.list(unit_test_db, entity.id, None)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_count_by_category_ids_query(self, unit_test_db: Session):
        """测试count_by_category_ids - 查询功能"""
        # 准备测试数据
        entity = product = Product(name="依赖查询测试", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(product)
        unit_test_db.commit()
        entity = SKU(sku_code="TEST查询测试", price=Decimal("10.00"), is_active=True, product_id=product.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SKURepository.count_by_category_ids(unit_test_db, 0)
        
        # 验证查询结果
        assert result >= 0  # count方法返回int

    def test_update_single_field(self, unit_test_db: Session):
        """测试update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        """
        # 准备测试数据
        from tests.factories.product_catalog_factories import SKUFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = SKUFactory.create()
        original_sku_code = entity.sku_code
        
        # 执行Repository方法（只更新name）
        update_data = {"name": "更新后数据"}
        result = SKURepository.update(unit_test_db, entity, update_data)  # TODO: 根据实际方法签名调整
        
        # 验证目标字段已更新
        assert result.name == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.sku_code == original_sku_code
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(SKU).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据"
        assert db_entity.sku_code == original_sku_code
    
    def test_update_multiple_fields(self, unit_test_db: Session):
        """测试update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        """
        from tests.factories.product_catalog_factories import SKUFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = SKUFactory.create()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "name": "更新后数据1",
            "sku_code": "更新后数据2"
        }
        result = SKURepository.update(unit_test_db, entity, update_data)
        
        # 验证所有字段已更新
        assert result.name == "更新后数据1"
        assert result.sku_code == "更新后数据2"
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(SKU).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据1"
        assert db_entity.sku_code == "更新后数据2"
    
    def test_update_transaction_commit(self, unit_test_db: Session):
        """测试update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        """
        from tests.factories.product_catalog_factories import SKUFactory, ProductCatalogFactoryManager
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        entity = SKUFactory.create()
        
        update_data = {"name": "事务测试数据"}
        result = SKURepository.update(unit_test_db, entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(SKU).filter_by(id=entity.id).first()
        assert db_entity.name == "事务测试数据"
    
    def test_update_specialized_method(self, unit_test_db: Session):
        """测试update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = SKUFactory.create(status='active')
        # result = SKURepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    def test_soft_delete_success(self, unit_test_db: Session):
        """测试soft_delete - 删除成功"""
        # 准备测试数据
        entity = product = Product(name="依赖待删除数据", status="active", sort_order=1, view_count=1, sale_count=1)
        unit_test_db.add(product)
        unit_test_db.commit()
        entity = SKU(sku_code="TEST待删除数据", price=Decimal("10.00"), is_active=True, product_id=product.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        SKURepository.soft_delete(unit_test_db, entity)
        
        # 验证软删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(SKU).filter_by(id=entity_id).first()
        assert db_entity is not None  # 记录仍存在
        # 验证软删除标记（根据模型字段选择）
        if hasattr(db_entity, 'is_deleted'):
            assert db_entity.is_deleted == True
        if hasattr(db_entity, 'is_active'):
            assert db_entity.is_active == False

