# Auto-generated test file
# Generated at: 20251015_204719
# Target path: tests/unit/test_repositories/test_order_management_repositories.py
# Do NOT edit this file manually - regenerate from source models

"""
Auto Generated Test - Repository Layer

文件路径: tests/unit/test_repositories/test_order_management_repositories.py
生成时间: 2025-10-15 20:47:19
生成工具: tools/generate_test_template.py v3.0
模块: order_management

测试类型: 单元测试 - Repository数据访问层
测试策略: SQLite内存数据库
测试重点: 
- CRUD操作正确性
- 查询条件和过滤逻辑
- 事务提交和回滚
- 边界情况和错误处理

符合标准: 
- testing-standards.md - 四层架构测试策略
- architecture/overview.md - Repository模式标准

[CHECK:TEST-001] [CHECK:DEV-009]
"""

import pytest
from typing import List, Optional
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timedelta
from decimal import Decimal

# 导入测试基础设施
from tests.conftest import unit_test_db

# 导入Repository类
from app.modules.order_management.repository import (
    OrderRepository
)

# 导入模型类
from app.modules.order_management.models import (
    Order
)


@pytest.mark.unit
@pytest.mark.repositories
class TestOrderRepository:
    """
    OrderRepository 数据访问层测试
    
    测试范围:
    - 17 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_get_user_by_id_found(self, unit_test_db: Session):
        """测试get_user_by_id - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_user_by_id(1)
        
        # 验证结果
        assert result is not None
        assert result.id == entity.id
    
    def test_get_user_by_id_not_found(self, unit_test_db: Session):
        """测试get_user_by_id - 数据不存在"""
        result = OrderRepository(unit_test_db).get_user_by_id("nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_get_product_by_id_found(self, unit_test_db: Session):
        """测试get_product_by_id - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_product_by_id(1)
        
        # 验证结果
        assert result is not None
        assert result.id == entity.id
    
    def test_get_product_by_id_not_found(self, unit_test_db: Session):
        """测试get_product_by_id - 数据不存在"""
        result = OrderRepository(unit_test_db).get_product_by_id("nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_get_sku_by_id_found(self, unit_test_db: Session):
        """测试get_sku_by_id - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_sku_by_id(1)
        
        # 验证结果
        assert result is not None
        assert result.id == entity.id
    
    def test_get_sku_by_id_not_found(self, unit_test_db: Session):
        """测试get_sku_by_id - 数据不存在"""
        result = OrderRepository(unit_test_db).get_sku_by_id("nonexistent_value_12345")
        
        # 验证结果
        assert result is None

    def test_save_order_minimal_fields(self, unit_test_db: Session):
        """测试save_order - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        # 创建最小实体（只填必填字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        
        # 构造被测实体: Order - 只填必填字段
        entity = Order(
            order_number="测试",
            status="active",
            subtotal=Decimal("1.00"),
            shipping_fee=Decimal("1.00"),
            discount_amount=Decimal("99.99"),
            total_amount=Decimal("99.99"),
            user_id=user.id
        )
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).save_order(entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_save_order_full_fields(self, unit_test_db: Session):
        """测试save_order - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        # 创建完整实体（填充所有字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        
        # 构造被测实体: Order - 填充所有字段
        entity = Order(
            order_number="完整测试",
            status="active",
            subtotal=Decimal("1.00"),
            shipping_fee=Decimal("1.00"),
            discount_amount=Decimal("99.99"),
            total_amount=Decimal("99.99"),
            shipping_address="完整测试",
            receiver_name="完整测试",
            receiver_phone="完整测试",
            shipping_method="完整测试",
            notes="完整测试",
            user_id=user.id
        )
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).save_order(entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_save_order_transaction_commit(self, unit_test_db: Session):
        """测试save_order - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        # 创建完整实体（填充所有字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        
        # 构造被测实体: Order - 填充所有字段
        entity = Order(
            order_number="完整测试",
            status="active",
            subtotal=Decimal("1.00"),
            shipping_fee=Decimal("1.00"),
            discount_amount=Decimal("99.99"),
            total_amount=Decimal("99.99"),
            shipping_address="完整测试",
            receiver_name="完整测试",
            receiver_phone="完整测试",
            shipping_method="完整测试",
            notes="完整测试",
            user_id=user.id
        )
        
        result = OrderRepository(unit_test_db).save_order(entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_save_order_item_minimal_fields(self, unit_test_db: Session):
        """测试save_order_item - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        from tests.factories.order_management_factories import OrderFactory
        from tests.factories.product_catalog_factories import ProductFactory
        from tests.factories.product_catalog_factories import ProductCatalogFactoryManager
        from tests.factories.unknown_factories import Product_skuFactory
        from tests.factories.unknown_factories import UnknownFactoryManager
        # 创建最小实体（只填必填字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        # 准备依赖实体: Order (同模块)
        OrderFactory._meta.sqlalchemy_session = unit_test_db
        order = OrderFactory.create(user_id=user.id)
        # 设置product_catalog模块所有Factory的session
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Product (跨模块)
        product = ProductFactory.create()
        # 设置unknown模块所有Factory的session
        UnknownFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Product_sku (跨模块)
        product_sku = Product_skuFactory.create()
        
        # 构造被测实体: OrderItem - 只填必填字段
        entity = OrderItem(
            sku_code="TEST测试",
            product_name="测试",
            sku_name="TEST测试",
            quantity=10,
            unit_price=Decimal("99.99"),
            total_price=Decimal("99.99"),
            order_id=order.id,
            product_id=product.id,
            sku_id=product_sku.id
        )
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).save_order_item(entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_save_order_item_full_fields(self, unit_test_db: Session):
        """测试save_order_item - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        from tests.factories.order_management_factories import OrderFactory
        from tests.factories.product_catalog_factories import ProductFactory
        from tests.factories.product_catalog_factories import ProductCatalogFactoryManager
        from tests.factories.unknown_factories import Product_skuFactory
        from tests.factories.unknown_factories import UnknownFactoryManager
        # 创建完整实体（填充所有字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        # 准备依赖实体: Order (同模块)
        OrderFactory._meta.sqlalchemy_session = unit_test_db
        order = OrderFactory.create(user_id=user.id)
        # 设置product_catalog模块所有Factory的session
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Product (跨模块)
        product = ProductFactory.create()
        # 设置unknown模块所有Factory的session
        UnknownFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Product_sku (跨模块)
        product_sku = Product_skuFactory.create()
        
        # 构造被测实体: OrderItem - 填充所有字段
        entity = OrderItem(
            sku_code="TEST完整测试",
            product_name="完整测试",
            sku_name="TEST完整测试",
            product_attributes="完整测试",
            product_image_url="https://example.com/完整测试",
            quantity=10,
            unit_price=Decimal("99.99"),
            total_price=Decimal("99.99"),
            order_id=order.id,
            product_id=product.id,
            sku_id=product_sku.id
        )
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).save_order_item(entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_save_order_item_transaction_commit(self, unit_test_db: Session):
        """测试save_order_item - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        from tests.factories.order_management_factories import OrderFactory
        from tests.factories.product_catalog_factories import ProductFactory
        from tests.factories.product_catalog_factories import ProductCatalogFactoryManager
        from tests.factories.unknown_factories import Product_skuFactory
        from tests.factories.unknown_factories import UnknownFactoryManager
        # 创建完整实体（填充所有字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        # 准备依赖实体: Order (同模块)
        OrderFactory._meta.sqlalchemy_session = unit_test_db
        order = OrderFactory.create(user_id=user.id)
        # 设置product_catalog模块所有Factory的session
        ProductCatalogFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Product (跨模块)
        product = ProductFactory.create()
        # 设置unknown模块所有Factory的session
        UnknownFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Product_sku (跨模块)
        product_sku = Product_skuFactory.create()
        
        # 构造被测实体: OrderItem - 填充所有字段
        entity = OrderItem(
            sku_code="TEST完整测试",
            product_name="完整测试",
            sku_name="TEST完整测试",
            product_attributes="完整测试",
            product_image_url="https://example.com/完整测试",
            quantity=10,
            unit_price=Decimal("99.99"),
            total_price=Decimal("99.99"),
            order_id=order.id,
            product_id=product.id,
            sku_id=product_sku.id
        )
        
        result = OrderRepository(unit_test_db).save_order_item(entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_save_status_history_minimal_fields(self, unit_test_db: Session):
        """测试save_status_history - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        from tests.factories.order_management_factories import OrderFactory
        # 创建最小实体（只填必填字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        # 准备依赖实体: Order (同模块)
        OrderFactory._meta.sqlalchemy_session = unit_test_db
        order = OrderFactory.create(user_id=user.id)
        
        # 构造被测实体: OrderStatusHistory - 只填必填字段
        entity = OrderStatusHistory(
            new_status="测试",
            order_id=order.id
        )
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).save_status_history(entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_save_status_history_full_fields(self, unit_test_db: Session):
        """测试save_status_history - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        from tests.factories.order_management_factories import OrderFactory
        # 创建完整实体（填充所有字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        # 准备依赖实体: Order (同模块)
        OrderFactory._meta.sqlalchemy_session = unit_test_db
        order = OrderFactory.create(user_id=user.id)
        
        # 构造被测实体: OrderStatusHistory - 填充所有字段
        entity = OrderStatusHistory(
            old_status="完整测试",
            new_status="完整测试",
            remark="完整测试",
            order_id=order.id,
            operator_id=user.id
        )
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).save_status_history(entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_save_status_history_transaction_commit(self, unit_test_db: Session):
        """测试save_status_history - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        from tests.factories.order_management_factories import OrderFactory
        # 创建完整实体（填充所有字段）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        # 准备依赖实体: Order (同模块)
        OrderFactory._meta.sqlalchemy_session = unit_test_db
        order = OrderFactory.create(user_id=user.id)
        
        # 构造被测实体: OrderStatusHistory - 填充所有字段
        entity = OrderStatusHistory(
            old_status="完整测试",
            new_status="完整测试",
            remark="完整测试",
            order_id=order.id,
            operator_id=user.id
        )
        
        result = OrderRepository(unit_test_db).save_status_history(entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Order).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_order_by_id_found(self, unit_test_db: Session):
        """测试get_order_by_id - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_order_by_id(entity.id)
        
        # 验证结果
        assert result is not None
        assert result.id == entity.id
    
    def test_get_order_by_id_not_found(self, unit_test_db: Session):
        """测试get_order_by_id - 数据不存在"""
        result = OrderRepository(unit_test_db).get_order_by_id(999999)
        
        # 验证结果
        assert result is None

    def test_get_order_with_items_found(self, unit_test_db: Session):
        """测试get_order_with_items - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_order_with_items(entity.id)
        
        # 验证结果
        assert result is not None
        assert result.id == entity.id
    
    def test_get_order_with_items_not_found(self, unit_test_db: Session):
        """测试get_order_with_items - 数据不存在"""
        result = OrderRepository(unit_test_db).get_order_with_items(999999)
        
        # 验证结果
        assert result is None

    def test_list_orders_query(self, unit_test_db: Session):
        """测试list_orders - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = OrderRepository(unit_test_db).list_orders(user_id=entity.id, status=entity, skip=0, limit=0)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_get_order_items_found(self, unit_test_db: Session):
        """测试get_order_items - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_order_items(entity.id, user_id=None)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），这里只验证方法正确执行并返回list类型即可
        if result:
            assert any(item.id == entity.id for item in result)
    
    def test_get_order_items_not_found(self, unit_test_db: Session):
        """测试get_order_items - 数据不存在"""
        result = OrderRepository(unit_test_db).get_order_items(999999, user_id=None)
        
        assert isinstance(result, list)
        # not_found测试不验证len(result)==0，因为数据库中可能有其他测试创建的数据
        assert len(result) == 0

    def test_get_order_status_history_found(self, unit_test_db: Session):
        """测试get_order_status_history - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_order_status_history(entity.id)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），这里只验证方法正确执行并返回list类型即可
        if result:
            assert any(item.id == entity.id for item in result)
    
    def test_get_order_status_history_not_found(self, unit_test_db: Session):
        """测试get_order_status_history - 数据不存在"""
        result = OrderRepository(unit_test_db).get_order_status_history(999999)
        
        assert isinstance(result, list)
        # not_found测试不验证len(result)==0，因为数据库中可能有其他测试创建的数据
        assert len(result) == 0

    def test_get_orders_by_status_found(self, unit_test_db: Session):
        """测试get_orders_by_status - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).get_orders_by_status(None, limit=1)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），这里只验证方法正确执行并返回list类型即可
        if result:
            assert any(item.id == entity.id for item in result)
    
    def test_get_orders_by_status_not_found(self, unit_test_db: Session):
        """测试get_orders_by_status - 数据不存在"""
        result = OrderRepository(unit_test_db).get_orders_by_status("nonexistent_value", "nonexistent_value")
        
        assert isinstance(result, list)
        # not_found测试不验证len(result)==0，因为数据库中可能有其他测试创建的数据
        assert len(result) == 0

    def test_get_inventory_stock_for_update_single_field(self, unit_test_db: Session):
        """测试get_inventory_stock_for_update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
        # 准备测试数据
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        # 创建最小实体（用于更新测试）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        
        # 构造被测实体: Order - 只填必填字段
        entity = Order(
            order_number="测试",
            status="active",
            subtotal=Decimal("1.00"),
            shipping_fee=Decimal("1.00"),
            discount_amount=Decimal("99.99"),
            total_amount=Decimal("99.99"),
            user_id=user.id
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        original_order_number = entity.order_number
        
        # 执行Repository方法（只更新status）
        update_data = {"status": "更新后数据"}
        result = OrderRepository(unit_test_db).get_inventory_stock_for_update(entity, update_data)
        
        # 验证目标字段已更新
        assert result.status == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.order_number == original_order_number
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Order).filter_by(id=entity.id).first()
        assert db_entity.status == "更新后数据"
        assert db_entity.order_number == original_order_number
    
    def test_get_inventory_stock_for_update_multiple_fields(self, unit_test_db: Session):
        """测试get_inventory_stock_for_update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        模式: 参数传递 - 通过update_data字典传递多个更新字段
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        # 创建最小实体（用于更新测试）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        
        # 构造被测实体: Order - 只填必填字段
        entity = Order(
            order_number="测试",
            status="active",
            subtotal=Decimal("1.00"),
            shipping_fee=Decimal("1.00"),
            discount_amount=Decimal("99.99"),
            total_amount=Decimal("99.99"),
            user_id=user.id
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "status": "更新后数据1",
            "order_number": "更新后数据2"
        }
        result = OrderRepository(unit_test_db).get_inventory_stock_for_update(entity, update_data)
        
        # 验证所有字段已更新
        assert result.status == "更新后数据1"
        assert result.order_number == "更新后数据2"
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Order).filter_by(id=entity.id).first()
        assert db_entity.status == "更新后数据1"
        assert db_entity.order_number == "更新后数据2"
    
    def test_get_inventory_stock_for_update_transaction_commit(self, unit_test_db: Session):
        """测试get_inventory_stock_for_update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        # 创建最小实体（用于更新测试）
        # 设置user_auth模块所有Factory的session
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User (跨模块)
        user = UserFactory.create()
        
        # 构造被测实体: Order - 只填必填字段
        entity = Order(
            order_number="测试",
            status="active",
            subtotal=Decimal("1.00"),
            shipping_fee=Decimal("1.00"),
            discount_amount=Decimal("99.99"),
            total_amount=Decimal("99.99"),
            user_id=user.id
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        update_data = {"status": "事务测试数据"}
        result = OrderRepository(unit_test_db).get_inventory_stock_for_update(entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Order).filter_by(id=entity.id).first()
        assert db_entity.status == "事务测试数据"
    
    def test_get_inventory_stock_for_update_specialized_method(self, unit_test_db: Session):
        """测试get_inventory_stock_for_update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = OrderFactory.create(status='active')
        # result = OrderRepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    def test_calculate_order_statistics_query(self, unit_test_db: Session):
        """测试calculate_order_statistics - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).calculate_order_statistics(user_id=entity.id)
        
        # 验证查询结果
        assert result is not None

    def test_commit_query(self, unit_test_db: Session):
        """测试commit - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).commit()
        
        # 验证查询结果
        # 方法返回None，验证执行成功即可

    def test_rollback_query(self, unit_test_db: Session):
        """测试rollback - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).rollback()
        
        # 验证查询结果
        # 方法返回None，验证执行成功即可

    def test_refresh_query(self, unit_test_db: Session):
        """测试refresh - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Order(order_number="查询测试", status="active", subtotal=Decimal("1.00"), shipping_fee=Decimal("1.00"), discount_amount=Decimal("99.99"), total_amount=Decimal("99.99"), user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = OrderRepository(unit_test_db).refresh(None)
        
        # 验证查询结果
        # 方法返回None，验证执行成功即可

