# Auto-generated test file
# Generated at: 20251017_075431
# Target path: tests/unit/test_repositories/test_user_auth_repositories.py
# Do NOT edit this file manually - regenerate from source models

"""
Auto Generated Test - Repository Layer

文件路径: tests/unit/test_repositories/test_user_auth_repositories.py
生成时间: 2025-10-17 07:54:30
生成工具: tools/generate_test_template.py v3.0
模块: user_auth

测试类型: 单元测试 - Repository数据访问层
测试策略: SQLite内存数据库
测试重点: 
- CRUD操作正确性
- 查询条件和过滤逻辑
- 事务提交和回滚
- 边界情况和错误处理

符合标准: 
- testing-standards.md - 四层架构测试策略
- architecture/overview.md - Repository模式标准

[CHECK:TEST-001] [CHECK:DEV-009]
"""

import pytest
from typing import List, Optional
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timedelta
from decimal import Decimal

# 导入测试基础设施
from tests.conftest import unit_test_db

# 导入Repository类
from app.modules.user_auth.repository import (
    UserRepository, RoleRepository, PermissionRepository, UserRoleRepository, RolePermissionRepository, SessionRepository
)

# 导入模型类
from app.modules.user_auth.models import (
    Permission, Role, RolePermission, Session, User, UserRole
)


@pytest.mark.unit
@pytest.mark.repositories
class TestUserRepository:
    """
    UserRepository 数据访问层测试
    
    测试范围:
    - 15 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
# 创建最小实体（只填必填字段）
        # 构造被测实体: User - 只填必填字段
        entity = User(
            username="测试",
            email="email_测试",
            password_hash="测试",
            is_active=True,
            status="active",
            email_verified=True,
            phone_verified=True,
            two_factor_enabled=True,
            failed_login_attempts=1,
            role="user"
        )
        
        # 执行Repository方法
        result = UserRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(User).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
# 创建完整实体（填充所有字段）
        # 构造被测实体: User - 填充所有字段
        entity = User(
            username="完整测试",
            email="email_完整测试",
            password_hash="完整测试",
            is_active=True,
            status="active",
            email_verified=True,
            phone_verified=True,
            two_factor_enabled=True,
            failed_login_attempts=1,
            locked_until=datetime.now(),
            last_login_at=datetime.now(),
            phone="完整测试",
            real_name="完整测试",
            role="user",
            wx_openid="完整测试",
            wx_unionid="完整测试",
            deleted_at=datetime.now()
        )
        
        # 执行Repository方法
        result = UserRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(User).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
# 创建完整实体（填充所有字段）
        # 构造被测实体: User - 填充所有字段
        entity = User(
            username="完整测试",
            email="email_完整测试",
            password_hash="完整测试",
            is_active=True,
            status="active",
            email_verified=True,
            phone_verified=True,
            two_factor_enabled=True,
            failed_login_attempts=1,
            locked_until=datetime.now(),
            last_login_at=datetime.now(),
            phone="完整测试",
            real_name="完整测试",
            role="user",
            wx_openid="完整测试",
            wx_unionid="完整测试",
            deleted_at=datetime.now()
        )
        
        result = UserRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(User).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.get_by_id(unit_test_db, entity.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = UserRepository.get_by_id(unit_test_db, 999999)
        
        # 验证结果
        assert result is None

    def test_get_by_username_found(self, unit_test_db: Session):
        """测试get_by_username - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.get_by_username(unit_test_db, entity.username)
        
        # 验证结果
        assert result is not None

    def test_get_by_username_not_found(self, unit_test_db: Session):
        """测试get_by_username - 数据不存在"""
        result = UserRepository.get_by_username(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_get_by_email_found(self, unit_test_db: Session):
        """测试get_by_email - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.get_by_email(unit_test_db, entity.email)
        
        # 验证结果
        assert result is not None

    def test_get_by_email_not_found(self, unit_test_db: Session):
        """测试get_by_email - 数据不存在"""
        result = UserRepository.get_by_email(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_get_by_username_or_email_found(self, unit_test_db: Session):
        """测试get_by_username_or_email - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.get_by_username_or_email(unit_test_db, entity.username)
        
        # 验证结果
        assert result is not None

    def test_get_by_username_or_email_not_found(self, unit_test_db: Session):
        """测试get_by_username_or_email - 数据不存在"""
        result = UserRepository.get_by_username_or_email(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_get_by_phone_found(self, unit_test_db: Session):
        """测试get_by_phone - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.get_by_phone(unit_test_db, entity.phone)
        
        # 验证结果
        assert result is not None

    def test_get_by_phone_not_found(self, unit_test_db: Session):
        """测试get_by_phone - 数据不存在"""
        result = UserRepository.get_by_phone(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_get_by_wx_openid_found(self, unit_test_db: Session):
        """测试get_by_wx_openid - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.get_by_wx_openid(unit_test_db, entity.wx_openid)
        
        # 验证结果
        assert result is not None

    def test_get_by_wx_openid_not_found(self, unit_test_db: Session):
        """测试get_by_wx_openid - 数据不存在"""
        result = UserRepository.get_by_wx_openid(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_check_exists_found(self, unit_test_db: Session):
        """测试check_exists - 查询到数据"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.check_exists(unit_test_db, entity.username, entity.email)
        
        # 验证结果
        assert result is True
    
    def test_check_exists_not_found(self, unit_test_db: Session):
        """测试check_exists - 数据不存在"""
        result = UserRepository.check_exists(unit_test_db, "nonexistent_value", "nonexistent_value")
        
        assert result is False

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = UserRepository.list(unit_test_db, 0, 100, False, entity.status, entity.role, "search_value")
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_count_query(self, unit_test_db: Session):
        """测试count - 查询功能"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.count(unit_test_db)
        
        # 验证查询结果
        assert result >= 0  # count方法返回int

    def test_update_single_field(self, unit_test_db: Session):
        """测试update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
        # 准备测试数据
# 创建最小实体（用于更新测试）
        # 构造被测实体: User - 只填必填字段
        entity = User(
            username="测试",
            email="email_测试",
            password_hash="测试",
            is_active=True,
            status="active",
            email_verified=True,
            phone_verified=True,
            two_factor_enabled=True,
            failed_login_attempts=1,
            role="user"
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        original_is_active = entity.is_active
        
        # 执行Repository方法（只更新real_name）
        update_data = {"real_name": "更新后数据"}
        result = UserRepository.update(unit_test_db, entity, update_data)
        
        # 验证目标字段已更新
        assert result.real_name == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.is_active == original_is_active
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(User).filter_by(id=entity.id).first()
        assert db_entity.real_name == "更新后数据"
        assert db_entity.is_active == original_is_active
    
    def test_update_multiple_fields(self, unit_test_db: Session):
        """测试update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        模式: 参数传递 - 通过update_data字典传递多个更新字段
        """
# 创建最小实体（用于更新测试）
        # 构造被测实体: User - 只填必填字段
        entity = User(
            username="测试",
            email="email_测试",
            password_hash="测试",
            is_active=True,
            status="active",
            email_verified=True,
            phone_verified=True,
            two_factor_enabled=True,
            failed_login_attempts=1,
            role="user"
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "real_name": "更新后数据1",
            "is_active": False
        }
        result = UserRepository.update(unit_test_db, entity, update_data)
        
        # 验证所有字段已更新
        assert result.real_name == "更新后数据1"
        assert result.is_active == False
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(User).filter_by(id=entity.id).first()
        assert db_entity.real_name == "更新后数据1"
        assert db_entity.is_active == False
    
    def test_update_transaction_commit(self, unit_test_db: Session):
        """测试update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
# 创建最小实体（用于更新测试）
        # 构造被测实体: User - 只填必填字段
        entity = User(
            username="测试",
            email="email_测试",
            password_hash="测试",
            is_active=True,
            status="active",
            email_verified=True,
            phone_verified=True,
            two_factor_enabled=True,
            failed_login_attempts=1,
            role="user"
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        update_data = {"real_name": "事务测试数据"}
        result = UserRepository.update(unit_test_db, entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(User).filter_by(id=entity.id).first()
        assert db_entity.real_name == "事务测试数据"
    
    def test_update_specialized_method(self, unit_test_db: Session):
        """测试update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = UserFactory.create(status='active')
        # result = UserRepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    # TODO: 测试专用更新方法 update_login_info
    # 这是一个专用更新方法，只修改特定字段，需要根据业务逻辑手动编写测试
    # 方法签名: [('user', 'User', 'positional'), ('ip_address', 'Optional[str]', 'positional')]
    # 返回类型: User
    

    def test_increment_failed_login_query(self, unit_test_db: Session):
        """测试increment_failed_login - 查询功能"""
        # 准备测试数据
        entity = User(username="查询测试", email="email_查询测试", password_hash="查询测试", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRepository.increment_failed_login(unit_test_db, entity)
        
        # 验证查询结果
        assert result is not None

    def test_soft_delete_success(self, unit_test_db: Session):
        """测试soft_delete - 删除成功"""
        # 准备测试数据
        entity = User(username="待删除数据", email="email_待删除数据", password_hash="待删除数据", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        UserRepository.soft_delete(unit_test_db, entity)
        unit_test_db.commit()  # 提交删除操作
        
        # 验证软删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(User).filter_by(id=entity_id).first()
        assert db_entity is not None  # 记录仍存在
        # 验证软删除标记（根据模型字段选择）
        if hasattr(db_entity, 'is_deleted'):
            assert db_entity.is_deleted == True
        if hasattr(db_entity, 'is_active'):
            assert db_entity.is_active == False

    def test_hard_delete_success(self, unit_test_db: Session):
        """测试hard_delete - 删除成功"""
        # 准备测试数据
        entity = User(username="待删除数据", email="email_待删除数据", password_hash="待删除数据", is_active=True, status="active", email_verified=True, phone_verified=True, two_factor_enabled=True, failed_login_attempts=1, role="user")
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        UserRepository.hard_delete(unit_test_db, entity)
        unit_test_db.commit()  # 提交删除操作
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(User).filter_by(id=entity_id).first()
        assert db_entity is None  # 记录已物理删除




@pytest.mark.unit
@pytest.mark.repositories
class TestRoleRepository:
    """
    RoleRepository 数据访问层测试
    
    测试范围:
    - 7 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
# 创建最小实体（只填必填字段）
        # 构造被测实体: Role - 只填必填字段
        entity = Role(
            name="测试",
            level=1
        )
        
        # 执行Repository方法
        result = RoleRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Role).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
# 创建完整实体（填充所有字段）
        # 构造被测实体: Role - 填充所有字段
        entity = Role(
            name="完整测试",
            description="完整测试",
            level=1
        )
        
        # 执行Repository方法
        result = RoleRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Role).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
# 创建完整实体（填充所有字段）
        # 构造被测实体: Role - 填充所有字段
        entity = Role(
            name="完整测试",
            description="完整测试",
            level=1
        )
        
        result = RoleRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Role).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备测试数据
        entity = Role(name="查询测试", level=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = RoleRepository.get_by_id(unit_test_db, entity.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = RoleRepository.get_by_id(unit_test_db, 999999)
        
        # 验证结果
        assert result is None

    def test_get_by_name_found(self, unit_test_db: Session):
        """测试get_by_name - 查询到数据"""
        # 准备测试数据
        entity = Role(name="查询测试", level=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = RoleRepository.get_by_name(unit_test_db, entity.name)
        
        # 验证结果
        assert result is not None

    def test_get_by_name_not_found(self, unit_test_db: Session):
        """测试get_by_name - 数据不存在"""
        result = RoleRepository.get_by_name(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = Role(name="查询测试", level=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = RoleRepository.list(unit_test_db, 0, 100)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_update_single_field(self, unit_test_db: Session):
        """测试update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
        # 准备测试数据
# 创建最小实体（用于更新测试）
        # 构造被测实体: Role - 只填必填字段
        entity = Role(
            name="测试",
            level=1
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        original_description = entity.description
        
        # 执行Repository方法（只更新name）
        update_data = {"name": "更新后数据"}
        result = RoleRepository.update(unit_test_db, entity, update_data)
        
        # 验证目标字段已更新
        assert result.name == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.description == original_description
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Role).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据"
        assert db_entity.description == original_description
    
    def test_update_multiple_fields(self, unit_test_db: Session):
        """测试update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        模式: 参数传递 - 通过update_data字典传递多个更新字段
        """
# 创建最小实体（用于更新测试）
        # 构造被测实体: Role - 只填必填字段
        entity = Role(
            name="测试",
            level=1
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "name": "更新后数据1",
            "description": "更新后数据2"
        }
        result = RoleRepository.update(unit_test_db, entity, update_data)
        
        # 验证所有字段已更新
        assert result.name == "更新后数据1"
        assert result.description == "更新后数据2"
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Role).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据1"
        assert db_entity.description == "更新后数据2"
    
    def test_update_transaction_commit(self, unit_test_db: Session):
        """测试update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
# 创建最小实体（用于更新测试）
        # 构造被测实体: Role - 只填必填字段
        entity = Role(
            name="测试",
            level=1
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        update_data = {"name": "事务测试数据"}
        result = RoleRepository.update(unit_test_db, entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Role).filter_by(id=entity.id).first()
        assert db_entity.name == "事务测试数据"
    
    def test_update_specialized_method(self, unit_test_db: Session):
        """测试update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = RoleFactory.create(status='active')
        # result = RoleRepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    def test_delete_success(self, unit_test_db: Session):
        """测试delete - 删除成功"""
        # 准备测试数据
        entity = Role(name="待删除数据", level=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        RoleRepository.delete(unit_test_db, entity)
        unit_test_db.commit()  # 提交删除操作
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Role).filter_by(id=entity_id).first()
        assert db_entity is None  # 记录已物理删除

    def test_get_user_count_found(self, unit_test_db: Session):
        """测试get_user_count - 查询到数据"""
        # 准备测试数据
        entity = Role(name="查询测试", level=1)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = RoleRepository.get_user_count(unit_test_db, entity.id)
        
        # 验证结果
        assert isinstance(result, int)
        assert result >= 0  # count方法返回非负整数

    def test_get_user_count_not_found(self, unit_test_db: Session):
        """测试get_user_count - 数据不存在"""
        result = RoleRepository.get_user_count(unit_test_db, 999999)
        
        # 验证结果
        assert result == 0  # count方法返回0




@pytest.mark.unit
@pytest.mark.repositories
class TestPermissionRepository:
    """
    PermissionRepository 数据访问层测试
    
    测试范围:
    - 6 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
# 创建最小实体（只填必填字段）
        # 构造被测实体: Permission - 只填必填字段
        entity = Permission(
            name="测试",
            resource="测试",
            action="测试"
        )
        
        # 执行Repository方法
        result = PermissionRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Permission).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
# 创建完整实体（填充所有字段）
        # 构造被测实体: Permission - 填充所有字段
        entity = Permission(
            name="完整测试",
            resource="完整测试",
            action="完整测试",
            description="完整测试"
        )
        
        # 执行Repository方法
        result = PermissionRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Permission).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
# 创建完整实体（填充所有字段）
        # 构造被测实体: Permission - 填充所有字段
        entity = Permission(
            name="完整测试",
            resource="完整测试",
            action="完整测试",
            description="完整测试"
        )
        
        result = PermissionRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Permission).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备测试数据
        entity = Permission(name="查询测试", resource="查询测试", action="查询测试")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = PermissionRepository.get_by_id(unit_test_db, entity.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = PermissionRepository.get_by_id(unit_test_db, 999999)
        
        # 验证结果
        assert result is None

    def test_get_by_name_found(self, unit_test_db: Session):
        """测试get_by_name - 查询到数据"""
        # 准备测试数据
        entity = Permission(name="查询测试", resource="查询测试", action="查询测试")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = PermissionRepository.get_by_name(unit_test_db, entity.name)
        
        # 验证结果
        assert result is not None

    def test_get_by_name_not_found(self, unit_test_db: Session):
        """测试get_by_name - 数据不存在"""
        result = PermissionRepository.get_by_name(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_list_query(self, unit_test_db: Session):
        """测试list - 查询功能"""
        # 准备测试数据
        entity = Permission(name="查询测试", resource="查询测试", action="查询测试")
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        results = PermissionRepository.list(unit_test_db, entity.resource, entity.action, 0, 100)
        
        # 验证查询结果
        assert isinstance(results, list)  # 返回列表

    def test_update_single_field(self, unit_test_db: Session):
        """测试update - 单字段更新
        
        符合标准: testing-standards.md 第2.3节 - 只更新一个字段，验证其他字段不变
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
        # 准备测试数据
# 创建最小实体（用于更新测试）
        # 构造被测实体: Permission - 只填必填字段
        entity = Permission(
            name="测试",
            resource="测试",
            action="测试"
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        original_resource = entity.resource
        
        # 执行Repository方法（只更新name）
        update_data = {"name": "更新后数据"}
        result = PermissionRepository.update(unit_test_db, entity, update_data)
        
        # 验证目标字段已更新
        assert result.name == "更新后数据"
        
        # ✅ 验证其他字段未变化
        assert result.resource == original_resource
        
        # 验证数据库已更新
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Permission).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据"
        assert db_entity.resource == original_resource
    
    def test_update_multiple_fields(self, unit_test_db: Session):
        """测试update - 多字段更新
        
        符合标准: testing-standards.md 第2.3节 - 同时更新多个字段
        模式: 参数传递 - 通过update_data字典传递多个更新字段
        """
# 创建最小实体（用于更新测试）
        # 构造被测实体: Permission - 只填必填字段
        entity = Permission(
            name="测试",
            resource="测试",
            action="测试"
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法（同时更新多个字段）
        update_data = {
            "name": "更新后数据1",
            "resource": "更新后数据2"
        }
        result = PermissionRepository.update(unit_test_db, entity, update_data)
        
        # 验证所有字段已更新
        assert result.name == "更新后数据1"
        assert result.resource == "更新后数据2"
        
        # 验证持久化
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Permission).filter_by(id=entity.id).first()
        assert db_entity.name == "更新后数据1"
        assert db_entity.resource == "更新后数据2"
    
    def test_update_transaction_commit(self, unit_test_db: Session):
        """测试update - 事务提交验证
        
        符合标准: testing-standards.md 第2.5节 - 验证更新真正写入数据库
        模式: 参数传递 - 通过update_data字典传递更新字段
        """
# 创建最小实体（用于更新测试）
        # 构造被测实体: Permission - 只填必填字段
        entity = Permission(
            name="测试",
            resource="测试",
            action="测试"
        )
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        update_data = {"name": "事务测试数据"}
        result = PermissionRepository.update(unit_test_db, entity, update_data)
        
        # 验证事务已提交
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Permission).filter_by(id=entity.id).first()
        assert db_entity.name == "事务测试数据"
    
    def test_update_specialized_method(self, unit_test_db: Session):
        """测试update - 专用方法测试（如有）
        
        符合标准: testing-standards.md 第2.3节 - 测试特殊更新方法
        示例: update_status, update_password, activate, deactivate等
        """
        # TODO: 如果有专用更新方法，在这里测试
        # 例如:
        # entity = PermissionFactory.create(status='active')
        # result = PermissionRepository.update_status(unit_test_db, entity.id, 'inactive')
        # assert result.status == 'inactive'
        pass

    def test_delete_success(self, unit_test_db: Session):
        """测试delete - 删除成功"""
        # 准备测试数据
        entity = Permission(name="待删除数据", resource="待删除数据", action="待删除数据")
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        PermissionRepository.delete(unit_test_db, entity)
        unit_test_db.commit()  # 提交删除操作
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Permission).filter_by(id=entity_id).first()
        assert db_entity is None  # 记录已物理删除




@pytest.mark.unit
@pytest.mark.repositories
class TestUserRoleRepository:
    """
    UserRoleRepository 数据访问层测试
    
    测试范围:
    - 6 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import RoleFactory
        # 创建最小实体（只填必填字段）
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        # 准备依赖实体: Role (同模块)
        RoleFactory._meta.sqlalchemy_session = unit_test_db
        role = RoleFactory.create()
        
        # 构造被测实体: UserRole - 只填必填字段
        entity = UserRole(
            user_id=user.id,
            role_id=role.id
        )
        
        # 执行Repository方法
        result = UserRoleRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        
        # 验证默认值（如果模型定义了default）
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化（联合主键查询）
        db_entity = unit_test_db.query(UserRole).filter_by(user_id=result.user_id, role_id=result.role_id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import RoleFactory
        # 使用Factory Boy创建完整实体
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        # 准备依赖实体: Role (同模块)
        RoleFactory._meta.sqlalchemy_session = unit_test_db
        role = RoleFactory.create()
        
        # 构造被测实体: UserRole - 填充所有字段
        entity = UserRole(
            assigned_at=datetime.now(),
            user_id=user.id,
            role_id=role.id,
            assigned_by=user.id
        )
        
        # 执行Repository方法
        result = UserRoleRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        # TODO: 验证各个字段值
        
        # 验证持久化
        db_entity = unit_test_db.query(UserRole).filter_by(user_id=result.user_id, role_id=result.role_id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.user_auth_factories import RoleFactory
        # 创建完整实体（填充所有字段）
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        # 准备依赖实体: Role (同模块)
        RoleFactory._meta.sqlalchemy_session = unit_test_db
        role = RoleFactory.create()
        
        # 构造被测实体: UserRole - 填充所有字段
        entity = UserRole(
            assigned_at=datetime.now(),
            user_id=user.id,
            role_id=role.id,
            assigned_by=user.id
        )
        
        result = UserRoleRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(UserRole).filter_by(user_id=result.user_id, role_id=result.role_id).first()
        assert db_entity is not None

    def test_get_found(self, unit_test_db: Session):
        """测试get - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        entity = UserRole(assigned_at=datetime.now(), user_id=user.id, role_id=role.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRoleRepository.get(unit_test_db, entity.user_id, entity.role_id)
        
        # 验证结果
        assert result is not None

    def test_get_not_found(self, unit_test_db: Session):
        """测试get - 数据不存在（复合主键）"""
        result = UserRoleRepository.get(unit_test_db, 999999, 999999)
        
        # 验证结果
        assert result is None

    def test_get_user_roles_found(self, unit_test_db: Session):
        """测试get_user_roles - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        entity = UserRole(assigned_at=datetime.now(), user_id=user.id, role_id=role.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRoleRepository.get_user_roles(unit_test_db, entity.user_id)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），
        # 这里只验证方法正确执行并返回list类型即可

    def test_get_user_roles_not_found(self, unit_test_db: Session):
        """测试get_user_roles - 数据不存在"""
        # 执行Repository方法（查询不存在的数据）
        result = UserRoleRepository.get_user_roles(unit_test_db, 999999)
        
        # 验证结果
        assert isinstance(result, list)
        assert len(result) == 0

    def test_get_role_users_found(self, unit_test_db: Session):
        """测试get_role_users - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        entity = UserRole(assigned_at=datetime.now(), user_id=user.id, role_id=role.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = UserRoleRepository.get_role_users(unit_test_db, entity.role_id, 0, 100)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），
        # 这里只验证方法正确执行并返回list类型即可

    def test_get_role_users_not_found(self, unit_test_db: Session):
        """测试get_role_users - 数据不存在"""
        # 执行Repository方法（查询不存在的数据）
        result = UserRoleRepository.get_role_users(unit_test_db, 999999)
        
        # 验证结果
        assert isinstance(result, list)
        assert len(result) == 0

    def test_delete_success(self, unit_test_db: Session):
        """测试delete - 删除成功"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        entity = UserRole(assigned_at=datetime.now(), user_id=user.id, role_id=role.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        user_id_val = entity.user_id
        role_id_val = entity.role_id
        
        # 执行Repository方法（使用主键参数）
        UserRoleRepository.delete(unit_test_db, user_id_val, role_id_val)
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(UserRole).filter_by(user_id=user_id_val, role_id=role_id_val).first()
        assert db_entity is None  # 记录已物理删除

    def test_delete_all_user_roles_success(self, unit_test_db: Session):
        """测试delete_all_user_roles - 删除成功"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        entity = UserRole(assigned_at=datetime.now(), user_id=user.id, role_id=role.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        user_id_val = entity.user_id
        role_id_val = entity.role_id
        
        # 执行Repository方法（使用主键参数）
        UserRoleRepository.delete_all_user_roles(unit_test_db, user_id_val)
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(UserRole).filter_by(user_id=user_id_val, role_id=role_id_val).first()
        assert db_entity is None  # 记录已物理删除




@pytest.mark.unit
@pytest.mark.repositories
class TestRolePermissionRepository:
    """
    RolePermissionRepository 数据访问层测试
    
    测试范围:
    - 6 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.user_auth_factories import RoleFactory
        from tests.factories.user_auth_factories import PermissionFactory
        from tests.factories.user_auth_factories import UserFactory
        # 创建最小实体（只填必填字段）
        # 准备依赖实体: Role (同模块)
        RoleFactory._meta.sqlalchemy_session = unit_test_db
        role = RoleFactory.create()
        # 准备依赖实体: Permission (同模块)
        PermissionFactory._meta.sqlalchemy_session = unit_test_db
        permission = PermissionFactory.create()
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        
        # 构造被测实体: RolePermission - 只填必填字段
        entity = RolePermission(
            role_id=role.id,
            permission_id=permission.id
        )
        
        # 执行Repository方法
        result = RolePermissionRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        
        # 验证默认值（如果模型定义了default）
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化（联合主键查询）
        db_entity = unit_test_db.query(RolePermission).filter_by(role_id=result.role_id, permission_id=result.permission_id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        """
        from tests.factories.user_auth_factories import RoleFactory
        from tests.factories.user_auth_factories import PermissionFactory
        from tests.factories.user_auth_factories import UserFactory
        # 使用Factory Boy创建完整实体
        # 准备依赖实体: Role (同模块)
        RoleFactory._meta.sqlalchemy_session = unit_test_db
        role = RoleFactory.create()
        # 准备依赖实体: Permission (同模块)
        PermissionFactory._meta.sqlalchemy_session = unit_test_db
        permission = PermissionFactory.create()
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        
        # 构造被测实体: RolePermission - 填充所有字段
        entity = RolePermission(
            granted_at=datetime.now(),
            role_id=role.id,
            permission_id=permission.id,
            granted_by=user.id
        )
        
        # 执行Repository方法
        result = RolePermissionRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        # TODO: 验证各个字段值
        
        # 验证持久化
        db_entity = unit_test_db.query(RolePermission).filter_by(role_id=result.role_id, permission_id=result.permission_id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
        from tests.factories.user_auth_factories import RoleFactory
        from tests.factories.user_auth_factories import PermissionFactory
        from tests.factories.user_auth_factories import UserFactory
        # 创建完整实体（填充所有字段）
        # 准备依赖实体: Role (同模块)
        RoleFactory._meta.sqlalchemy_session = unit_test_db
        role = RoleFactory.create()
        # 准备依赖实体: Permission (同模块)
        PermissionFactory._meta.sqlalchemy_session = unit_test_db
        permission = PermissionFactory.create()
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        
        # 构造被测实体: RolePermission - 填充所有字段
        entity = RolePermission(
            granted_at=datetime.now(),
            role_id=role.id,
            permission_id=permission.id,
            granted_by=user.id
        )
        
        result = RolePermissionRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(RolePermission).filter_by(role_id=result.role_id, permission_id=result.permission_id).first()
        assert db_entity is not None

    def test_get_found(self, unit_test_db: Session):
        """测试get - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        # 准备依赖实体: Permission
        from tests.factories.user_auth_factories import PermissionFactory
        permission = PermissionFactory.create()
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = RolePermission(granted_at=datetime.now(), role_id=role.id, permission_id=permission.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = RolePermissionRepository.get(unit_test_db, entity.role_id, entity.permission_id)
        
        # 验证结果
        assert result is not None

    def test_get_not_found(self, unit_test_db: Session):
        """测试get - 数据不存在（复合主键）"""
        result = RolePermissionRepository.get(unit_test_db, 999999, 999999)
        
        # 验证结果
        assert result is None

    def test_get_role_permissions_found(self, unit_test_db: Session):
        """测试get_role_permissions - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        # 准备依赖实体: Permission
        from tests.factories.user_auth_factories import PermissionFactory
        permission = PermissionFactory.create()
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = RolePermission(granted_at=datetime.now(), role_id=role.id, permission_id=permission.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = RolePermissionRepository.get_role_permissions(unit_test_db, entity.role_id)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），
        # 这里只验证方法正确执行并返回list类型即可

    def test_get_role_permissions_not_found(self, unit_test_db: Session):
        """测试get_role_permissions - 数据不存在"""
        # 执行Repository方法（查询不存在的数据）
        result = RolePermissionRepository.get_role_permissions(unit_test_db, 999999)
        
        # 验证结果
        assert isinstance(result, list)
        assert len(result) == 0

    def test_get_user_permissions_found(self, unit_test_db: Session):
        """测试get_user_permissions - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        # 准备依赖实体: Permission
        from tests.factories.user_auth_factories import PermissionFactory
        permission = PermissionFactory.create()
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = RolePermission(granted_at=datetime.now(), role_id=role.id, permission_id=permission.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = RolePermissionRepository.get_user_permissions(unit_test_db, 1)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），
        # 这里只验证方法正确执行并返回list类型即可

    def test_get_user_permissions_not_found(self, unit_test_db: Session):
        """测试get_user_permissions - 数据不存在"""
        # 执行Repository方法（查询不存在的数据）
        result = RolePermissionRepository.get_user_permissions(unit_test_db, 999999)
        
        # 验证结果
        assert isinstance(result, list)
        assert len(result) == 0

    def test_delete_success(self, unit_test_db: Session):
        """测试delete - 删除成功"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        # 准备依赖实体: Permission
        from tests.factories.user_auth_factories import PermissionFactory
        permission = PermissionFactory.create()
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = RolePermission(granted_at=datetime.now(), role_id=role.id, permission_id=permission.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        role_id_val = entity.role_id
        permission_id_val = entity.permission_id
        
        # 执行Repository方法（使用主键参数）
        RolePermissionRepository.delete(unit_test_db, role_id_val, permission_id_val)
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(RolePermission).filter_by(role_id=role_id_val, permission_id=permission_id_val).first()
        assert db_entity is None  # 记录已物理删除

    def test_delete_all_role_permissions_success(self, unit_test_db: Session):
        """测试delete_all_role_permissions - 删除成功"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: Role
        from tests.factories.user_auth_factories import RoleFactory
        role = RoleFactory.create()
        # 准备依赖实体: Permission
        from tests.factories.user_auth_factories import PermissionFactory
        permission = PermissionFactory.create()
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = RolePermission(granted_at=datetime.now(), role_id=role.id, permission_id=permission.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        role_id_val = entity.role_id
        permission_id_val = entity.permission_id
        
        # 执行Repository方法（使用主键参数）
        RolePermissionRepository.delete_all_role_permissions(unit_test_db, role_id_val)
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(RolePermission).filter_by(role_id=role_id_val, permission_id=permission_id_val).first()
        assert db_entity is None  # 记录已物理删除




@pytest.mark.unit
@pytest.mark.repositories
class TestSessionRepository:
    """
    SessionRepository 数据访问层测试
    
    测试范围:
    - 9 个Repository方法
    - CRUD操作完整性
    - 查询逻辑正确性
    - 事务处理和数据一致性
    
    测试策略: SQLite内存数据库 + Factory Boy
    """
        
    def test_create_minimal_fields(self, unit_test_db: Session):
        """测试create - 最小必填字段创建
        
        符合标准: testing-standards.md 第2.1节 - 只填写必填字段，验证默认值
        数据准备策略: 最小实体构造，不使用Factory Boy
        """
        from tests.factories.user_auth_factories import UserFactory
        # 创建最小实体（只填必填字段）
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        
        # 构造被测实体: Session - 只填必填字段
        entity = Session(
            token_hash="测试",
            expires_at=datetime.now(),
            is_active=True,
            user_id=user.id
        )
        
        # 执行Repository方法
        result = SessionRepository.create(unit_test_db, entity)
        
        # 验证必填字段
        assert result is not None
        assert result.id is not None  # 验证ID已生成
        
        # 验证默认值（Column(default=...)定义的值）
        # 示例: assert result.is_active == True
        # 示例: assert result.status == "active"
        # TODO: 根据实际模型补充默认值验证
        
        # 验证数据已持久化
        db_entity = unit_test_db.query(Session).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_full_fields(self, unit_test_db: Session):
        """测试create - 完整字段创建
        
        符合标准: testing-standards.md 第2.1节 - 填写所有字段，验证保存正确
        数据准备策略: 使用构造函数填充所有字段
        """
        from tests.factories.user_auth_factories import UserFactory
        # 创建完整实体（填充所有字段）
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        
        # 构造被测实体: Session - 填充所有字段
        entity = Session(
            token_hash="完整测试",
            expires_at=datetime.now(),
            last_accessed_at=datetime.now(),
            is_active=True,
            ip_address="完整测试",
            user_agent="完整测试",
            user_id=user.id
        )
        
        # 执行Repository方法
        result = SessionRepository.create(unit_test_db, entity)
        
        # 验证所有字段保存正确
        assert result is not None
        assert result.id is not None
        # TODO: 验证其他字段值正确保存
        
        # 验证持久化
        db_entity = unit_test_db.query(Session).filter_by(id=result.id).first()
        assert db_entity is not None
    
    def test_create_transaction_commit(self, unit_test_db: Session):
        """测试create - 事务提交验证
        
        符合标准: testing-standards.md 第2.1节 - 验证数据真正写入数据库
        """
        from tests.factories.user_auth_factories import UserFactory
        # 创建完整实体（填充所有字段）
        # 准备依赖实体: User (同模块)
        UserFactory._meta.sqlalchemy_session = unit_test_db
        user = UserFactory.create()
        
        # 构造被测实体: Session - 填充所有字段
        entity = Session(
            token_hash="完整测试",
            expires_at=datetime.now(),
            last_accessed_at=datetime.now(),
            is_active=True,
            ip_address="完整测试",
            user_agent="完整测试",
            user_id=user.id
        )
        
        result = SessionRepository.create(unit_test_db, entity)
        
        # 验证事务已提交（expire后重新查询能找到）
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Session).filter_by(id=result.id).first()
        assert db_entity is not None

    def test_get_by_id_found(self, unit_test_db: Session):
        """测试get_by_id - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="查询测试", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SessionRepository.get_by_id(unit_test_db, entity.id)
        
        # 验证结果
        assert result is not None

    def test_get_by_id_not_found(self, unit_test_db: Session):
        """测试get_by_id - 数据不存在"""
        result = SessionRepository.get_by_id(unit_test_db, 999999)
        
        # 验证结果
        assert result is None

    def test_get_by_token_hash_found(self, unit_test_db: Session):
        """测试get_by_token_hash - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="查询测试", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SessionRepository.get_by_token_hash(unit_test_db, entity.token_hash)
        
        # 验证结果
        assert result is not None

    def test_get_by_token_hash_not_found(self, unit_test_db: Session):
        """测试get_by_token_hash - 数据不存在"""
        result = SessionRepository.get_by_token_hash(unit_test_db, "nonexistent_value")
        
        # 验证结果
        assert result is None

    def test_get_user_active_sessions_found(self, unit_test_db: Session):
        """测试get_user_active_sessions - 查询到数据"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="关联数据", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SessionRepository.get_user_active_sessions(unit_test_db, entity.user_id)
        
        # 验证结果
        assert isinstance(result, list)
        # 注意：复杂join查询可能返回空列表（依赖完整的关联链），
        # 这里只验证方法正确执行并返回list类型即可

    def test_get_user_active_sessions_not_found(self, unit_test_db: Session):
        """测试get_user_active_sessions - 数据不存在"""
        # 执行Repository方法（查询不存在的数据）
        result = SessionRepository.get_user_active_sessions(unit_test_db, 999999)
        
        # 验证结果
        assert isinstance(result, list)
        assert len(result) == 0

    # TODO: 测试专用更新方法 update_last_accessed
    # 这是一个专用更新方法，只修改特定字段，需要根据业务逻辑手动编写测试
    # 方法签名: [('session', 'UserSession', 'positional')]
    # 返回类型: UserSession
    

    def test_deactivate_query(self, unit_test_db: Session):
        """测试deactivate - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="查询测试", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SessionRepository.deactivate(unit_test_db, entity)
        
        # 验证查询结果
        assert result is not None

    def test_deactivate_user_sessions_query(self, unit_test_db: Session):
        """测试deactivate_user_sessions - 查询功能"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="查询测试", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行Repository方法
        result = SessionRepository.deactivate_user_sessions(unit_test_db, entity.user_id)
        
        # 验证查询结果
        # 方法返回None，验证执行成功即可

    def test_delete_expired_sessions_physical_delete(self, unit_test_db: Session):
        """测试delete_expired_sessions - 批量删除功能
        
        符合标准: testing-standards.md 第2.4节 - 验证批量删除功能
        """
        # 创建测试数据（使用手动创建避免Factory SubFactory session问题）
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="批量删除测试", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        
        # 执行批量删除（方法根据内部条件删除数据）
        result = SessionRepository.delete_expired_sessions(unit_test_db)
        unit_test_db.commit()  # 提交删除操作
        
        # ✅ 验证返回结果（通常返回删除的数量）
        if result is not None:
            assert isinstance(result, int)
            assert result >= 0
        
        # 验证数据库操作成功
        total_count = unit_test_db.query(Session).count()
        assert total_count >= 0
    
    def test_delete_expired_sessions_cascade_delete(self, unit_test_db: Session):
        """测试delete_expired_sessions - 级联删除（如有关联数据）
        
        符合标准: testing-standards.md 第2.4节 - 验证关联数据的物理删除
        """
        # TODO: 如果该模型有关联数据，验证级联删除行为
        # 根据外键定义的ondelete行为:
        # - CASCADE: 子记录应被删除
        # - SET NULL: 子记录外键应为NULL
        # - RESTRICT: 应抛出异常
        
        # 示例:
        # parent = ParentFactory.create()
        # child = ChildFactory.create(parent_id=parent.id)
        # SessionRepository.delete_expired_sessions(unit_test_db, parent.id)
        # 
        # # CASCADE情况
        # db_child = unit_test_db.query(Child).filter_by(id=child.id).first()
        # assert db_child is None
        pass
    
    def test_delete_expired_sessions_batch_delete(self, unit_test_db: Session):
        """测试delete_expired_sessions - 批量物理删除（如有批量方法）
        
        符合标准: testing-standards.md 第2.4节 - 验证批量删除
        """
        # TODO: 如果有批量删除方法(delete_many, bulk_delete)，在这里测试
        # 示例:
        # entities = SessionFactory.create_batch(3)
        # ids = [e.id for e in entities]
        # SessionRepository.delete_many(unit_test_db, ids)
        # 
        # for entity_id in ids:
        #     db_entity = unit_test_db.query(Session).filter_by(id=entity_id).first()
        #     assert db_entity is None
        pass

    def test_delete_success(self, unit_test_db: Session):
        """测试delete - 删除成功"""
        # 准备测试数据
        from tests.factories.user_auth_factories import UserAuthFactoryManager
        UserAuthFactoryManager.setup_factories(unit_test_db)
        # 准备依赖实体: User
        from tests.factories.user_auth_factories import UserFactory
        user = UserFactory.create()
        entity = Session(token_hash="待删除数据", expires_at=datetime.now(), last_accessed_at=datetime.now(), is_active=True, user_id=user.id)
        unit_test_db.add(entity)
        unit_test_db.commit()
        entity_id = entity.id
        
        # 执行Repository方法（传递对象）
        SessionRepository.delete(unit_test_db, entity)
        unit_test_db.commit()  # 提交删除操作
        
        # 验证硬删除
        unit_test_db.expire_all()
        db_entity = unit_test_db.query(Session).filter_by(id=entity_id).first()
        assert db_entity is None  # 记录已物理删除

