# Auto-generated test file
# Generated at: 20251019_122252
# Target path: tests/factories/inventory_management_factories.py
# Do NOT edit this file manually - regenerate from source models

"""
智能生成的Factory Boy测试数据工厂 - inventory_management模块

自动生成时间: 2025-10-19 12:22:48
生成模型数量: 3
智能特性: 
- 自动推断字段类型和合理测试值
- 处理外键关系和唯一约束  
- 支持复杂业务场景数据创建

符合标准:
- [CHECK:TEST-002] Factory Boy测试数据标准
- [CHECK:DEV-009] 代码生成质量标准

使用示例:
    from tests.factories.inventory_management_factories import *
    
    # 创建测试数据
    # (具体示例依据实际生成的Factory类)
"""

import factory
import factory.fuzzy
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from sqlalchemy.orm import Session

# 处理表重定义警告的配置
import warnings
warnings.filterwarnings('ignore', message='.*declarative base.*')
warnings.filterwarnings('ignore', message='.*Table.*already defined.*')

from app.modules.inventory_management.models import (
    InventoryTransaction, InventoryReservation, InventoryStock
)


class InventoryStockFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的InventoryStock工厂类"""
    
    class Meta:
        model = InventoryStock
        sqlalchemy_session_persistence = "commit"

    sku_id = factory.Sequence(lambda n: n + 1)  # 跨模块外键，使用序列ID
    total_quantity = factory.Faker('random_int', min=1, max=1000)
    available_quantity = factory.Faker('random_int', min=1, max=1000)
    reserved_quantity = factory.Faker('random_int', min=1, max=1000)
    warning_threshold = factory.Faker('random_int', min=1, max=1000)
    critical_threshold = factory.Faker('random_int', min=1, max=1000)
    is_active = True


class InventoryTransactionFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的InventoryTransaction工厂类"""
    
    class Meta:
        model = InventoryTransaction
        sqlalchemy_session_persistence = "commit"

    sku = factory.SubFactory(InventoryStockFactory)
    transaction_type = factory.Faker('word')
    quantity_change = factory.Faker('random_int', min=1, max=1000)
    quantity_before = factory.Faker('random_int', min=1, max=1000)
    quantity_after = factory.Faker('random_int', min=1, max=1000)
    reference_type = factory.Faker('text', max_nb_chars=200)
    reference_id = factory.Faker('text', max_nb_chars=200)
    operator_id = factory.Faker('random_int', min=1, max=1000)
    reason = factory.Faker('text', max_nb_chars=200)
    notes = factory.Faker('text', max_nb_chars=200)


class InventoryReservationFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的InventoryReservation工厂类"""
    
    class Meta:
        model = InventoryReservation
        sqlalchemy_session_persistence = "commit"

    sku = factory.SubFactory(InventoryStockFactory)
    reservation_type = factory.Faker('word')
    reference_id = factory.Faker('text', max_nb_chars=200)
    quantity = factory.Faker('random_int', min=1, max=1000)
    expires_at = factory.LazyFunction(lambda: datetime.now() + timedelta(days=30))
    is_active = True


class InventoryManagementFactoryManager:
    """智能生成的inventory_management模块工厂管理器
    
    提供便捷的测试数据创建方法和常见业务场景的数据组合
    """
    
    @staticmethod
    def setup_factories(session):
        """设置所有工厂的数据库会话"""
        InventoryStockFactory._meta.sqlalchemy_session = session
        InventoryTransactionFactory._meta.sqlalchemy_session = session
        InventoryReservationFactory._meta.sqlalchemy_session = session

    @staticmethod
    def create_sample_data(session) -> dict:
        """创建样本测试数据 - 按依赖顺序创建避免外键约束失败"""
        InventoryManagementFactoryManager.setup_factories(session)
        
        data = {}
        
        # 导入所有跨模块依赖的Factory
        from tests.factories.product_catalog_factories import SKUFactory, ProductFactory, CategoryFactory, BrandFactory
        
        # 设置所有Factory的session
        SKUFactory._meta.sqlalchemy_session = session
        ProductFactory._meta.sqlalchemy_session = session
        CategoryFactory._meta.sqlalchemy_session = session
        BrandFactory._meta.sqlalchemy_session = session
        
        data = {}
        
        # 1. 创建Category，满足外键约束
        data['category'] = CategoryFactory()
        # 2. 创建Brand，满足外键约束
        data['brand'] = BrandFactory()
        # 3. 创建Product，满足外键约束
        data['product'] = ProductFactory(category_id=data["category"].id, brand_id=data["brand"].id)
        # 4. 创建Sku，满足外键约束
        data['sku'] = SKUFactory(product_id=data["product"].id)
        
        # 5. 创建InventoryStock
        data['inventorystock'] = InventoryStockFactory(sku_id=data['sku'].id)
        # 6. 创建InventoryTransaction
        data['inventorytransaction'] = InventoryTransactionFactory()
        # 7. 创建InventoryReservation
        data['inventoryreservation'] = InventoryReservationFactory()
        
        session.commit()
        return data
        
    @staticmethod
    def create_test_scenario(session, scenario: str = 'basic') -> dict:
        """创建特定测试场景的数据"""
        return InventoryManagementFactoryManager.create_sample_data(session)