# Auto-generated test file
# Generated at: 20251019_192336
# Target path: tests/factories/order_management_factories.py
# Do NOT edit this file manually - regenerate from source models

"""
智能生成的Factory Boy测试数据工厂 - order_management模块

自动生成时间: 2025-10-19 19:23:36
生成模型数量: 3
智能特性: 
- 自动推断字段类型和合理测试值
- 处理外键关系和唯一约束  
- 支持复杂业务场景数据创建

符合标准:
- [CHECK:TEST-002] Factory Boy测试数据标准
- [CHECK:DEV-009] 代码生成质量标准

使用示例:
    from tests.factories.order_management_factories import *
    
    # 创建测试数据
    # (具体示例依据实际生成的Factory类)
"""

import factory
import factory.fuzzy
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from sqlalchemy.orm import Session

# 处理表重定义警告的配置
import warnings
warnings.filterwarnings('ignore', message='.*declarative base.*')
warnings.filterwarnings('ignore', message='.*Table.*already defined.*')

from app.modules.order_management.models import (
    Order, OrderItem, OrderStatusHistory
)


class OrderFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的Order工厂类"""
    
    class Meta:
        model = Order
        sqlalchemy_session_persistence = "commit"

    order_number = factory.Sequence(lambda n: f'order_number_{n}')
    user_id = factory.Sequence(lambda n: n + 1)  # 跨模块外键，使用序列ID
    status = factory.Faker('text', max_nb_chars=200)
    subtotal = factory.LazyAttribute(lambda obj: Decimal('10.00'))
    shipping_fee = factory.LazyAttribute(lambda obj: Decimal('10.00'))
    discount_amount = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    total_amount = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    shipping_address = factory.Faker('address')
    receiver_name = factory.Sequence(lambda n: f'receiver_name_{n}')
    receiver_phone = factory.Faker('phone_number')
    shipping_method = factory.Faker('text', max_nb_chars=200)
    notes = factory.Faker('text', max_nb_chars=200)
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class OrderItemFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的OrderItem工厂类"""
    
    class Meta:
        model = OrderItem
        sqlalchemy_session_persistence = "commit"

    order = factory.SubFactory(OrderFactory)
    product_id = factory.Sequence(lambda n: n + 1)  # 跨模块外键，使用序列ID
    sku_id = factory.Sequence(lambda n: n + 1)  # 跨模块外键，使用序列ID
    sku_code = factory.Sequence(lambda n: f'SKU_CODE_{n:06d}')
    product_name = factory.Sequence(lambda n: f'product_name_{n}')
    sku_name = factory.Sequence(lambda n: f'sku_name_{n}')
    product_attributes = factory.LazyAttribute(lambda obj: {'color': 'blue', 'size': 'M'})
    product_image_url = factory.Faker('url')
    quantity = factory.Faker('random_int', min=1, max=1000)
    unit_price = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    total_price = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    created_at = factory.LazyFunction(datetime.now)


class OrderStatusHistoryFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的OrderStatusHistory工厂类"""
    
    class Meta:
        model = OrderStatusHistory
        sqlalchemy_session_persistence = "commit"

    order = factory.SubFactory(OrderFactory)
    old_status = factory.Faker('text', max_nb_chars=200)
    new_status = factory.Faker('text', max_nb_chars=200)
    remark = factory.Faker('text', max_nb_chars=200)
    operator_id = None  # 跨模块外键，使用None避免导入复杂性 (目标: User)
    created_at = factory.LazyFunction(datetime.now)


class OrderManagementFactoryManager:
    """智能生成的order_management模块工厂管理器
    
    提供便捷的测试数据创建方法和常见业务场景的数据组合
    """
    
    @staticmethod
    def setup_factories(session):
        """设置所有工厂的数据库会话"""
        OrderFactory._meta.sqlalchemy_session = session
        OrderItemFactory._meta.sqlalchemy_session = session
        OrderStatusHistoryFactory._meta.sqlalchemy_session = session

    @staticmethod
    def create_sample_data(session) -> dict:
        """创建样本测试数据 - 按依赖顺序创建避免外键约束失败"""
        OrderManagementFactoryManager.setup_factories(session)
        
        data = {}
        
        # 导入所有跨模块依赖的Factory
        from tests.factories.user_auth_factories import UserFactory
        from tests.factories.product_catalog_factories import ProductFactory, SKUFactory, CategoryFactory, BrandFactory
        
        # 设置所有Factory的session
        UserFactory._meta.sqlalchemy_session = session
        ProductFactory._meta.sqlalchemy_session = session
        SKUFactory._meta.sqlalchemy_session = session
        CategoryFactory._meta.sqlalchemy_session = session
        BrandFactory._meta.sqlalchemy_session = session
        
        data = {}
        
        # 1. 创建User，满足外键约束
        data['user'] = UserFactory()
        # 2. 创建Category，满足外键约束
        data['category'] = CategoryFactory()
        # 3. 创建Brand，满足外键约束
        data['brand'] = BrandFactory()
        # 4. 创建Product，满足外键约束
        data['product'] = ProductFactory(category_id=data["category"].id, brand_id=data["brand"].id)
        # 5. 创建Sku，满足外键约束
        data['sku'] = SKUFactory(product_id=data["product"].id)
        
        # 6. 创建Order
        data['order'] = OrderFactory(user_id=data['user'].id)
        # 7. 创建OrderItem
        data['orderitem'] = OrderItemFactory(order_id=data['order'].id, product_id=data['product'].id, sku_id=data['sku'].id)
        # 8. 创建OrderStatusHistory
        data['orderstatushistory'] = OrderStatusHistoryFactory(order_id=data['order'].id, operator_id=data['user'].id)
        
        session.commit()
        return data
        
    @staticmethod
    def create_test_scenario(session, scenario: str = 'basic') -> dict:
        """创建特定测试场景的数据"""
        return OrderManagementFactoryManager.create_sample_data(session)