# Auto-generated test file
# Generated at: 20251010_160645
# Target path: tests/factories/product_catalog_factories.py
# Do NOT edit this file manually - regenerate from source models

"""
智能生成的Factory Boy测试数据工厂 - product_catalog模块

自动生成时间: 2025-10-10 16:06:45
生成模型数量: 8
智能特性: 
- 自动推断字段类型和合理测试值
- 处理外键关系和唯一约束  
- 支持复杂业务场景数据创建

符合标准:
- [CHECK:TEST-002] Factory Boy测试数据标准
- [CHECK:DEV-009] 代码生成质量标准

使用示例:
    from tests.factories.product_catalog_factories import *
    
    # 创建测试数据
    user = UserFactory()
    role = RoleFactory()
    
    # 创建关联数据
    user_with_role = UserFactory(role=RoleFactory())
"""

import factory
import factory.fuzzy
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from sqlalchemy.orm import Session

# 处理表重定义警告的配置
import warnings
warnings.filterwarnings('ignore', message='.*declarative base.*')
warnings.filterwarnings('ignore', message='.*Table.*already defined.*')

from app.modules.product_catalog.models import (
    ProductTag, Category, ProductAttribute, SKU, Brand, ProductImage, Product, SKUAttribute
)


class BrandFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的Brand工厂类"""
    
    class Meta:
        model = Brand
        sqlalchemy_session_persistence = "commit"

    name = factory.Sequence(lambda n: f'name_{n}')
    slug = factory.Sequence(lambda n: f'slug_{n}')
    description = factory.Faker('text', max_nb_chars=200)
    logo_url = factory.Faker('url')
    website_url = factory.Faker('url')
    is_active = True
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)
    is_deleted = False
    deleted_at = factory.Faker('date_time_this_year')


class CategoryFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的Category工厂类"""
    
    class Meta:
        model = Category
        sqlalchemy_session_persistence = "commit"

    name = factory.Sequence(lambda n: f'name_{n}')
    description = factory.Faker('text', max_nb_chars=200)
    parent_id = None  # 自引用字段，避免循环依赖
    sort_order = factory.Faker('random_int', min=1, max=1000)
    is_active = True
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)
    is_deleted = False
    deleted_at = factory.Faker('date_time_this_year')


class ProductFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的Product工厂类"""
    
    class Meta:
        model = Product
        sqlalchemy_session_persistence = "commit"

    name = factory.Sequence(lambda n: f'name_{n}')
    description = factory.Faker('text', max_nb_chars=200)
    brand = factory.SubFactory(BrandFactory)
    category = factory.SubFactory(CategoryFactory)
    status = factory.Faker('word')
    published_at = factory.Faker('date_time_this_year')
    seo_title = factory.Faker('sentence', nb_words=4)
    seo_description = factory.Faker('text', max_nb_chars=200)
    seo_keywords = factory.Faker('text', max_nb_chars=200)
    sort_order = factory.Faker('random_int', min=1, max=1000)
    view_count = factory.Faker('random_int', min=1, max=1000)
    sale_count = factory.Faker('random_int', min=1, max=1000)
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)
    is_deleted = False
    deleted_at = factory.Faker('date_time_this_year')


class ProductTagFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的ProductTag工厂类"""
    
    class Meta:
        model = ProductTag
        sqlalchemy_session_persistence = "commit"

    product = factory.SubFactory(ProductFactory)
    tag_name = factory.Sequence(lambda n: f'tag_name_{n}')
    tag_type = factory.Faker('word')
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class ProductAttributeFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的ProductAttribute工厂类"""
    
    class Meta:
        model = ProductAttribute
        sqlalchemy_session_persistence = "commit"

    product = factory.SubFactory(ProductFactory)
    attribute_name = factory.Sequence(lambda n: f'attribute_name_{n}')
    attribute_value = factory.Faker('text', max_nb_chars=200)
    attribute_type = factory.Faker('word')
    is_searchable = factory.Faker('boolean')
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class SKUFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的SKU工厂类"""
    
    class Meta:
        model = SKU
        sqlalchemy_session_persistence = "commit"

    product = factory.SubFactory(ProductFactory)
    sku_code = factory.Sequence(lambda n: f'SKU_CODE_{n:06d}')
    name = factory.Sequence(lambda n: f'name_{n}')
    price = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    cost_price = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    market_price = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    weight = factory.LazyAttribute(lambda obj: Decimal('10.00'))
    volume = factory.LazyAttribute(lambda obj: Decimal('10.00'))
    is_active = True
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class ProductImageFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的ProductImage工厂类"""
    
    class Meta:
        model = ProductImage
        sqlalchemy_session_persistence = "commit"

    product = factory.SubFactory(ProductFactory)
    sku = factory.SubFactory(SKUFactory)
    image_url = factory.Faker('url')
    alt_text = factory.Faker('text', max_nb_chars=200)
    sort_order = factory.Faker('random_int', min=1, max=1000)
    is_primary = factory.Faker('boolean')
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class SKUAttributeFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的SKUAttribute工厂类"""
    
    class Meta:
        model = SKUAttribute
        sqlalchemy_session_persistence = "commit"

    sku = factory.SubFactory(SKUFactory)
    attribute_name = factory.Sequence(lambda n: f'attribute_name_{n}')
    attribute_value = factory.Faker('text', max_nb_chars=200)
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class ProductCatalogFactoryManager:
    """智能生成的product_catalog模块工厂管理器
    
    提供便捷的测试数据创建方法和常见业务场景的数据组合
    """
    
    @staticmethod
    def setup_factories(session):
        """设置所有工厂的数据库会话"""
        BrandFactory._meta.sqlalchemy_session = session
        CategoryFactory._meta.sqlalchemy_session = session
        ProductFactory._meta.sqlalchemy_session = session
        ProductTagFactory._meta.sqlalchemy_session = session
        ProductAttributeFactory._meta.sqlalchemy_session = session
        SKUFactory._meta.sqlalchemy_session = session
        ProductImageFactory._meta.sqlalchemy_session = session
        SKUAttributeFactory._meta.sqlalchemy_session = session

    @staticmethod
    def create_sample_data(session) -> dict:
        """创建样本测试数据 - 按依赖顺序创建避免外键约束失败"""
        ProductCatalogFactoryManager.setup_factories(session)
        
        data = {}
        data['brand'] = BrandFactory()  # 创建Brand实例
        data['category'] = CategoryFactory()  # 创建Category实例
        data['product'] = ProductFactory()  # 创建Product实例
        data['producttag'] = ProductTagFactory()  # 创建ProductTag实例
        data['productattribute'] = ProductAttributeFactory()  # 创建ProductAttribute实例
        data['sku'] = SKUFactory()  # 创建SKU实例
        data['productimage'] = ProductImageFactory()  # 创建ProductImage实例
        data['skuattribute'] = SKUAttributeFactory()  # 创建SKUAttribute实例
        
        session.commit()
        return data
        
    @staticmethod
    def create_test_scenario(session, scenario: str = 'basic') -> dict:
        """创建特定测试场景的数据"""
        return ProductCatalogFactoryManager.create_sample_data(session)