# Auto-generated test file
# Generated at: 20251013_083403
# Target path: tests/factories/shopping_cart_factories.py
# Do NOT edit this file manually - regenerate from source models

"""
智能生成的Factory Boy测试数据工厂 - shopping_cart模块

自动生成时间: 2025-10-13 08:34:02
生成模型数量: 2
智能特性: 
- 自动推断字段类型和合理测试值
- 处理外键关系和唯一约束  
- 支持复杂业务场景数据创建

符合标准:
- [CHECK:TEST-002] Factory Boy测试数据标准
- [CHECK:DEV-009] 代码生成质量标准

使用示例:
    from tests.factories.shopping_cart_factories import *
    
    # 创建测试数据
    # (具体示例依据实际生成的Factory类)
"""

import factory
import factory.fuzzy
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from sqlalchemy.orm import Session

# 处理表重定义警告的配置
import warnings
warnings.filterwarnings('ignore', message='.*declarative base.*')
warnings.filterwarnings('ignore', message='.*Table.*already defined.*')

from app.modules.shopping_cart.models import (
    CartItem, Cart
)


class CartFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的Cart工厂类"""
    
    class Meta:
        model = Cart
        sqlalchemy_session_persistence = "commit"

    user_id = factory.Sequence(lambda n: n + 1)  # 跨模块外键，使用序列ID
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class CartItemFactory(factory.alchemy.SQLAlchemyModelFactory):
    """智能生成的CartItem工厂类"""
    
    class Meta:
        model = CartItem
        sqlalchemy_session_persistence = "commit"

    cart = factory.SubFactory(CartFactory)
    sku_id = factory.Sequence(lambda n: n + 1)  # 跨模块外键，使用序列ID
    quantity = factory.Faker('random_int', min=1, max=1000)
    unit_price = factory.LazyAttribute(lambda obj: Decimal('99.99'))
    created_at = factory.LazyFunction(datetime.now)
    updated_at = factory.LazyFunction(datetime.now)


class ShoppingCartFactoryManager:
    """智能生成的shopping_cart模块工厂管理器
    
    提供便捷的测试数据创建方法和常见业务场景的数据组合
    """
    
    @staticmethod
    def setup_factories(session):
        """设置所有工厂的数据库会话"""
        CartFactory._meta.sqlalchemy_session = session
        CartItemFactory._meta.sqlalchemy_session = session

    @staticmethod
    def create_sample_data(session) -> dict:
        """创建样本测试数据 - 按依赖顺序创建避免外键约束失败"""
        ShoppingCartFactoryManager.setup_factories(session)
        
        data = {}
        data['cart'] = CartFactory()  # 创建Cart实例
        data['cartitem'] = CartItemFactory()  # 创建CartItem实例
        
        session.commit()
        return data
        
    @staticmethod
    def create_test_scenario(session, scenario: str = 'basic') -> dict:
        """创建特定测试场景的数据"""
        return ShoppingCartFactoryManager.create_sample_data(session)